### ISSUE TITLE
FAILED - RETRYING: Wait for the ServiceMonitor CRD to be created 

### ISSUE THREAD

**Issue by Alex-BlackMamba** [openshift/openshift-ansible#11111] opened 2019-02-01 07:29 UTC
I tried to install a 2 nodes cluster (3.11) on Centos7.5, but never succeeded by below reason:
I've already changed NM_CONTROLLED=yes in: 
/etc/sysconfig/network-scripts/ifcfg-eth0 (CentOS)

[root@master openshift]# cat /etc/sysconfig/network-scripts/ifcfg-eth0
# Created by cloud-init on instance boot automatically, do not edit.
#
NM_CONTROLLED=yes
BOOTPROTO=dhcp
DEVICE=eth0
HWADDR=fa:16:3e:d0:dc:b6
ONBOOT=yes
TYPE=Ethernet
USERCTL=no
[root@master openshift]#

Does anyone have some idea about this?

**Comment by Askill** [comment] 2019-02-21 15:20
Sorry, no idea but the same problem on a 1 Node installation.

**Comment by vrutkovs** [comment] 2019-03-24 14:28
Dupe of #10969

**Closed by vrutkovs** 2019-03-24 14:28 UTC
