### ISSUE TITLE
ca option injected into oidc configuration in master-config.yaml even when no ca is specified

### ISSUE THREAD

**Issue by mlbiam** [openshift/openshift-ansible#10216] opened 2018-09-25 02:30 UTC
#### Description

When specifying an oidc idp in your inventory with no certificate file attribute the playbooks are injecting the `ca` attribute with the value of `idpname_openid_ca.crt` where `idpname` is the name of the identity provider.  So as an example the following inventory variable: `openshift_master_identity_providers=[{"name": "unison","challenge": false,"login": true,"mappingMethod": "claim","kind": "OpenIDIdentityProvider","clientID": "openshift","clientSecret": "","claims": {"id": ["sub"],"preferredUsername": ["preferred_username"],"name": ["name"],"email": ["email"]},"urls": {"authorize": "https://idm.customer.com/auth/idp/OpenShiftIdP/auth","token":"https://idm.customer.com/auth/idp/OpenShiftIdP/token"}}]` will generate a `ca` attribute with the value `unison_openid_ca.crt`.  If your idp is signed by a commercial certificate or the certificate is already trusted by the servers because the CA has been imported into the trust store this causes an extra configuration that is not needed.   If the `ca` directive points to a file that doesn't exist the api server fails to start.

It appears this pull request implemented this issue - https://github.com/openshift/openshift-ansible/commit/845e90a0445339e221a6550d25e9c7a5734bf259#diff-37bf817a5aae06cfc3e26ff12c2c1d6c

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

2.4

If you're operating from a **git clone**:

* The output of `git describe`

```
release-3.10
```

##### Steps To Reproduce
1. add the above `openshift_master_identity_providers` to your inventory
2. deploy OKD 3.10

##### Expected Results
Describe what you expected to happen.

The `ca` should not be set if none is specified.  Based on the PR that introduced this issue, there should be a flag of some kind to disable this behavior.

**Comment by vrutkovs** [comment] 2018-09-26 08:44
Duplicate of #9988

>If your idp is signed by a commercial certificate or the certificate is already trusted by the servers because the CA has been imported into the trust store this causes an extra configuration that is not needed

This CA is used by API server, which is running in a static pod (a separate container). So importing CA into the host's trust store won't be sufficient. For clarity the trust store should be specified explicitly.

The installer assumes this file is already present on the host, if its not specified.

**Closed by vrutkovs** 2018-09-26 08:44 UTC

**Comment by mlbiam** [comment] 2018-09-26 11:32
> This CA is used by API server, which is running in a static pod (a separate container). So importing CA into the host's trust store won't be sufficient. For clarity the trust store should be specified explicitly.

This assertion is incorrect on multiple levels:

1. If the static pod were not trusting the certificate from the idp, why would openshift work without the `ca` directive?
2.  Requiring that a certificate be deployed for "clarity" is adding an additional step that is not needed.  Examples:
  a.  Using a commercial SSO solution signed by trusted commerical certificates
  b.  Corporate domain with an internal CA (ie FreeIPA)

This adds an additional and unnecessary burden onto deployers and I would suggest you relook at this approach as it gets deployed more you will be seeing more bug reports related to this decision.

**Comment by vrutkovs** [comment] 2018-09-26 11:42
>If the static pod were not trusting the certificate from the idp, why would openshift work without the ca directive?

It was using trust store from the container

>Using a commercial SSO solution signed by trusted commerical certificates

API server container trust store would be updated only during the build, so it won't be affected by changes to the host CA bundle which happened on 3.9
