### ISSUE TITLE
docker image "v1.2.0-rc1" breaks ansible docker version parsing.

### ISSUE THREAD

**Issue by gordillo-ramon** [openshift/openshift-ansible#1797] opened 2016-04-24 23:27 UTC
Hi.

# docker run --rm openshift/origin:latest version
openshift v1.2.0-rc1-17-g642f0af
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

Issue is related roles/openshift_docker/tasks/main.yml:

    l_image_tag: "{{ cli_image_version.stdout_lines[0].split(' ')[1].split('-')[0] }}"

when running with the previous result, it leads to "v1.2.0" and not "v1.2.0-rc1", so it breaks the version tag selection on docker images.

**Comment by sdodson** [comment] 2016-04-25 13:51
Thanks, Dupe of #1800 workaround documented in that issue.

**Closed** 2016-04-25 20:20 UTC
