### ISSUE TITLE
"update expected at most 1 arguments, got 2" from get_current_openshift_version.py

### ISSUE THREAD

**Issue by marksfink** [openshift/openshift-ansible#10435] opened 2018-10-17 22:36 UTC
#### Description

Receiving this error when running prequisites.yml when it gets to cluster_facts.yml and runs get_current_openshift_version.py.  This is on a new install.

##### Version

CentOS Linux release 7.5.1804 (Core)

ansible 2.7.0
  config file = /home/mark/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/mark/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

git describe:
openshift-ansible-3.11.24-1-4-g366d854

OUTPUT (with -vvv)

TASK [get openshift_current_version] ******************************************************************************************************************
task path: /home/mark/openshift-ansible/playbooks/init/cluster_facts.yml:10
Wednesday 17 October 2018  18:29:13 -0400 (0:00:01.224)       0:00:14.360 *****
Using module file /home/mark/openshift-ansible/roles/lib_utils/library/get_current_openshift_version.py
Using module file /home/mark/openshift-ansible/roles/lib_utils/library/get_current_openshift_version.py
<os-infra1.local> ESTABLISH SSH CONNECTION FOR USER: root
<os-infra1.local> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=30 -o ControlPath=/home/mark/.ansible/cp/%h-%r os-infra1.local '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
Using module file /home/mark/openshift-ansible/roles/lib_utils/library/get_current_openshift_version.py
<os-node1.local> ESTABLISH SSH CONNECTION FOR USER: root
<os-node1.local> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=30 -o ControlPath=/home/mark/.ansible/cp/%h-%r os-node1.local '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
Using module file /home/mark/openshift-ansible/roles/lib_utils/library/get_current_openshift_version.py
<os-node2.local> ESTABLISH SSH CONNECTION FOR USER: root
<os-node2.local> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=30 -o ControlPath=/home/mark/.ansible/cp/%h-%r os-node2.local '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<os-master1.local> ESTABLISH SSH CONNECTION FOR USER: root
<os-master1.local> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=30 -o ControlPath=/home/mark/.ansible/cp/%h-%r os-master1.local '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<os-infra1.local> (0, '\n{"invocation": {"module_args": {"deployment_type": "origin"}}, "changed": false, "ansible_facts": {}}\n', '')
ERROR! Unexpected Exception, this is probably a bug: update expected at most 1 arguments, got 2
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 156, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 291, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 325, in run
    results += self._wait_on_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 712, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 117, in inner
    results = func(self, iterator, one_pass=one_pass, max_passes=max_passes)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 615, in _process_pending_results
    self._variable_manager.set_host_facts(target_host, result_item['ansible_facts'].copy())
  File "/usr/lib/python2.7/site-packages/ansible/vars/manager.py", line 627, in set_host_facts
    self._fact_cache.update(host.name, facts)
TypeError: update expected at most 1 arguments, got 2
<os-node1.local> (0, '\n{"invocation": {"module_args": {"deployment_type": "origin"}}, "changed": false, "ansible_facts": {}}\n', '')
<os-node2.local> (0, '\n{"invocation": {"module_args": {"deployment_type": "origin"}}, "changed": false, "ansible_facts": {}}\n', '')
<os-master1.local> (0, '\n{"invocation": {"module_args": {"deployment_type": "origin"}}, "changed": false, "ansible_facts": {}}\n', '')

INVENTORY FILE

[OSEv3:children]
masters
etcd
nodes

[OSEv3:vars]
## Ansible user who can login to all nodes through SSH (e.g. ssh root@os-master1)
ansible_user=root

## Deployment type: "openshift-enterprise" or "origin"
openshift_deployment_type=origin
deployment_type=origin

## Specifies the major version
openshift_release=v3.11
openshift_pkg_version=-3.11.0
openshift_image_tag=v3.11.0
openshift_service_catalog_image_version=v3.11.0
template_service_broker_image_version=v3.11.0
openshift_metrics_image_version="v3.11"
openshift_logging_image_version="v3.11"
openshift_logging_elasticsearch_proxy_image_version="v1.0.0"
osm_use_cockpit=true
openshift_metrics_install_metrics=True
openshift_logging_install_logging=True

## Service address space,  /16 = 65,534 IPs
openshift_portal_net=172.30.0.0/16

## Pod address space
osm_cluster_network_cidr=10.128.0.0/14

## Subnet Length of each node, 9 = 510 IPs
osm_host_subnet_length=9

## Master API  port
openshift_master_api_port=443

## Master console port  (e.g. https://console.openshift.local:443)
openshift_master_console_port=443

## Clustering method
openshift_master_cluster_method=native

## Hostname used by nodes and other cluster internals
openshift_master_cluster_hostname=console-int.openshift.local

## Hostname used by platform users
openshift_master_cluster_public_hostname=console.openshift.local

## Application wildcard subdomain
openshift_master_default_subdomain=apps.openshift.local

## identity provider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

## Users being created in the cluster
openshift_master_htpasswd_users={'admin': '$apr1$A6mcBwiZ$gzCibDc6wOBNIV6fz1KKC.', 'user1': '$apr1$XEE4aMfW$0QJZ.eovQPL3IMJzpdV7I1'}

## Persistent storage, NFS
openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_host=zion.local
openshift_hosted_registry_storage_nfs_directory=/volume1/SHARED
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=50Gi

## Other vars
containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

#NFS check bug
openshift_enable_unsupported_configurations=True
#Another Bug 1569476 
skip_sanity_checks=true

openshift_node_kubelet_args="{'eviction-hard': ['memory.available<100Mi'], 'minimum-container-ttl-duration': ['10s'], 'maximum-dead-containers-per-container': ['2'], 'maximum-dead-containers': ['5'], 'pods-per-core': ['10'], 'max-pods': ['25'], 'image-gc-high-threshold': ['80'], 'image-gc-low-threshold': ['60']}"

[OSEv3:vars]

[masters]
os-master1.local

[etcd]
os-master1.local

[nodes]
os-master1.local openshift_node_labels="{'region': 'master'}"
os-infra1.local openshift_node_labels="{'region': 'infra'}"
os-node1.local openshift_node_labels="{'region': 'primary'}"
os-node2.local openshift_node_labels="{'region': 'primary'}"

**Comment by magick93** [comment] 2018-10-18 09:33
Try with ansible 2.6.x.

Ansible 2.7 isnt supported for 3.11.

**Comment by vrutkovs** [comment] 2018-10-18 09:38
Dupe of #10368

**Closed by vrutkovs** 2018-10-18 09:38 UTC

**Comment by marksfink** [comment] 2018-10-19 00:32
Ansible 2.6.5 worked fine.  Thanks!
