### ISSUE TITLE
Trying to build an openshift on AWS

### ISSUE THREAD

**Issue by wolfeidau** [openshift/openshift-ansible#1954] opened 2016-05-26 23:44 UTC
Just wanted to road test openshift and I am running into an error during build.

```
TASK [Evaluate oo_containerized_master_nodes] **********************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'hostvars[item].openshift.common.is_containerized | bool and (item in groups.oo_nodes_to_config and item in groups.oo_masters_to_config)' failed. The error was: error while evaluating conditional (hostvars[item].openshift.common.is_containerized | bool and (item in groups.oo_nodes_to_config and item in groups.oo_masters_to_config)): 'dict object' has no attribute 'openshift'\n\nThe error appears to have been in '/Users/markw/Code/ops/openshift-ansible/playbooks/common/openshift-node/config.yml': line 39, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - name: Evaluate oo_containerized_master_nodes\n    ^ here\n"}
```

Command I am running is.

```
AWS_PROFILE=XXX AWS_REGION=ap-southeast-2 bin/cluster create aws --deployment-type=origin mwolfe-openshift
```

Any tips or hints would be greatly appreciated.

**Comment by detiber** [comment] 2016-05-27 16:11
@wolfeidau bin/cluster is only community supported. I just attempted to replicate this and I am currently hitting a different issue: 
```
fatal: [jdetiber-node-compute-90727 -> jdetiber-master-6920e] => One or more undefined variables: 'openshift_master_hostnames' is undefined
```

**Comment by gordillo-ramon** [comment] 2016-05-28 00:14
I think it need to be added:

    openshift_master_hostnames: "{{ hostvars
                                    | oo_select_keys(groups['oo_masters_to_config'] | default([]))
                                    | oo_collect('openshift.common.all_hostnames')
                                    | oo_flatten | unique }}"

to playbook/common/openshift-node/config.yaml, in the ca section.

**Comment by wolfeidau** [comment] 2016-05-28 01:09
@detiber Is there a way I can get openshift running on AWS any other way?

@gordillo-ramon I will give that a shot, thanks for the hint!

**Comment by gordillo-ramon** [comment] 2016-05-28 10:30
What I wonder is if openshif_ca role needs that step. Indeed, I guess the problem is that it has been moved from openshift_master_ca role to it. 

As it is already present on openshift_master_certificates main tasks, is it possible just to delete it from openshift_ca role?

**Comment by abutcher** [comment] 2016-05-31 17:56
Openshift certificate related changes have been backed out via #1962 which should restore the breakage @detiber was hitting re: `openshift_master_hostnames`.

**Comment by detiber** [comment] 2016-05-31 17:57
This should be working again with the changes in #1962 we are going to wait to re-introduce those changes until after we finish the ansible 2.0 migration.

**Comment by detiber** [comment] 2016-05-31 17:58
Closing, since I'm not able to replicate now. Please re-open if this is still an issue.

**Closed by detiber** 2016-05-31 17:58 UTC
Labels: kind/bug, priority/P2
