### ISSUE TITLE
KeyError: 'openshift' in « openshift_facts | Gather hostnames for proxy configuration »

### ISSUE THREAD

**Issue by harobed** [openshift/openshift-ansible#1820] opened 2016-04-27 14:36 UTC
```
TASK: [openshift_facts | Gather hostnames for proxy configuration] ************
fatal: [atomic-test-etcd-1] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 589, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 793, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1017, in _executor_internal_inner
    complex_args = template.template(self.basedir, complex_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 14, in root
  File "/Users/stephane/projets/perso/test-openshift-atomic/upstream/filter_plugins/oo_filters.py", line 101, in oo_collect
    retval = [FilterModule.get_attr(d, attribute) for d in data]
  File "/Users/stephane/projets/perso/test-openshift-atomic/upstream/filter_plugins/oo_filters.py", line 47, in get_attr
    ptr = ptr[attr]
KeyError: 'openshift'

FATAL: all hosts have already failed -- aborting
```

```
$ git rev-parse HEAD
207b5aea8d619acb9622a351f54301c24598b08d
```

**Comment by detiber** [comment] 2016-04-27 14:46
@harobed can you provide more of the ansible output, usually this type of error occurs when one or more hosts fail earlier in the run.

**Comment by harobed** [comment] 2016-04-27 14:51
```
$ ansible-playbook -i hosts playbooks/byo/config.yml

PLAY [Populate config host groups] ********************************************

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [Evaluate oo_all_hosts] *************************************************
ok: [localhost] => (item=atomic-test-master-1)
ok: [localhost] => (item=atomic-test-node-1)
ok: [localhost] => (item=atomic-test-node-2)
ok: [localhost] => (item=atomic-test-etcd-1)

TASK: [Evaluate oo_masters] ***************************************************
ok: [localhost] => (item=atomic-test-master-1)

TASK: [Evaluate oo_etcd_to_config] ********************************************
ok: [localhost] => (item=atomic-test-etcd-1)

TASK: [Evaluate oo_masters_to_config] *****************************************
ok: [localhost] => (item=atomic-test-master-1)

TASK: [Evaluate oo_nodes_to_config] *******************************************
ok: [localhost] => (item=atomic-test-node-1)
ok: [localhost] => (item=atomic-test-node-2)

TASK: [Evaluate oo_nodes_to_config] *******************************************
skipping: [localhost] => (item=atomic-test-master-1)

TASK: [Evaluate oo_first_etcd] ************************************************
ok: [localhost]

TASK: [Evaluate oo_first_master] **********************************************
ok: [localhost]

TASK: [Evaluate oo_lb_to_config] **********************************************
skipping: [localhost]

TASK: [Evaluate oo_nfs_to_config] *********************************************
skipping: [localhost]

PLAY [Populate config host groups] ********************************************

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [fail ] *****************************************************************
skipping: [localhost]

TASK: [Evaluate oo_all_hosts] *************************************************
ok: [localhost] => (item=atomic-test-master-1)
ok: [localhost] => (item=atomic-test-node-1)
ok: [localhost] => (item=atomic-test-node-2)
ok: [localhost] => (item=atomic-test-etcd-1)

TASK: [Evaluate oo_masters] ***************************************************
ok: [localhost] => (item=atomic-test-master-1)

TASK: [Evaluate oo_etcd_to_config] ********************************************
ok: [localhost] => (item=atomic-test-etcd-1)

TASK: [Evaluate oo_masters_to_config] *****************************************
ok: [localhost] => (item=atomic-test-master-1)

TASK: [Evaluate oo_nodes_to_config] *******************************************
ok: [localhost] => (item=atomic-test-node-1)
ok: [localhost] => (item=atomic-test-node-2)

TASK: [Evaluate oo_nodes_to_config] *******************************************
skipping: [localhost] => (item=atomic-test-master-1)

TASK: [Evaluate oo_first_etcd] ************************************************
ok: [localhost]

TASK: [Evaluate oo_first_master] **********************************************
ok: [localhost]

TASK: [Evaluate oo_lb_to_config] **********************************************
skipping: [localhost]

TASK: [Evaluate oo_nfs_to_config] *********************************************
skipping: [localhost]

PLAY [Gather and set facts for node hosts] ************************************

GATHERING FACTS ***************************************************************
ok: [atomic-test-node-1]
ok: [atomic-test-node-2]

TASK: [openshift_facts | Verify Ansible version is greater than or equal to 1.9.4 and less than 2.0] ***
skipping: [atomic-test-node-1]
skipping: [atomic-test-node-2]

TASK: [openshift_facts | Detecting Operating System] **************************
ok: [atomic-test-node-1]
ok: [atomic-test-node-2]

TASK: [openshift_facts | set_fact ] *******************************************
ok: [atomic-test-node-2]
ok: [atomic-test-node-1]

TASK: [openshift_facts | set_fact ] *******************************************
ok: [atomic-test-node-1]
ok: [atomic-test-node-2]

TASK: [openshift_facts | Ensure PyYaml is installed] **************************
skipping: [atomic-test-node-1]
skipping: [atomic-test-node-2]

TASK: [openshift_facts | Gather Cluster facts and set is_containerized if needed] ***
ok: [atomic-test-node-2]
ok: [atomic-test-node-1]

TASK: [openshift_facts | Gather hostnames for proxy configuration] ************
ok: [atomic-test-node-2]
ok: [atomic-test-node-1]

TASK: [shell getent ahostsv4 {{ openshift.common.hostname }} | head -n 1 | awk '{ print $1 }'] ***
ok: [atomic-test-node-2]
ok: [atomic-test-node-1]

TASK: [Warn user about bad openshift_hostname values] *************************
skipping: [atomic-test-node-1]

PLAY [Set oo_options] *********************************************************

GATHERING FACTS ***************************************************************
ok: [atomic-test-node-2]
ok: [atomic-test-node-1]
ok: [atomic-test-etcd-1]
ok: [atomic-test-master-1]

TASK: [set_fact ] *************************************************************
ok: [atomic-test-node-2]
ok: [atomic-test-etcd-1]
ok: [atomic-test-master-1]
ok: [atomic-test-node-1]

TASK: [set_fact ] *************************************************************
ok: [atomic-test-node-1]
ok: [atomic-test-master-1]
ok: [atomic-test-node-2]
ok: [atomic-test-etcd-1]

TASK: [set_fact ] *************************************************************
ok: [atomic-test-node-1]
ok: [atomic-test-master-1]
ok: [atomic-test-etcd-1]
ok: [atomic-test-node-2]

TASK: [set_fact ] *************************************************************
ok: [atomic-test-master-1]
ok: [atomic-test-node-2]
ok: [atomic-test-etcd-1]
ok: [atomic-test-node-1]

TASK: [set_fact ] *************************************************************
ok: [atomic-test-node-1]
ok: [atomic-test-node-2]
ok: [atomic-test-etcd-1]
ok: [atomic-test-master-1]

TASK: [set_fact ] *************************************************************
ok: [atomic-test-node-2]
ok: [atomic-test-master-1]
ok: [atomic-test-etcd-1]
ok: [atomic-test-node-1]

PLAY [Set etcd facts needed for generating certs] *****************************

GATHERING FACTS ***************************************************************
ok: [atomic-test-etcd-1]

TASK: [openshift_facts | Verify Ansible version is greater than or equal to 1.9.4 and less than 2.0] ***
skipping: [atomic-test-etcd-1]

TASK: [openshift_facts | Detecting Operating System] **************************
ok: [atomic-test-etcd-1]

TASK: [openshift_facts | set_fact ] *******************************************
ok: [atomic-test-etcd-1]

TASK: [openshift_facts | set_fact ] *******************************************
ok: [atomic-test-etcd-1]

TASK: [openshift_facts | Ensure PyYaml is installed] **************************
skipping: [atomic-test-etcd-1]

TASK: [openshift_facts | Gather Cluster facts and set is_containerized if needed] ***
ok: [atomic-test-etcd-1]

TASK: [openshift_facts | Gather hostnames for proxy configuration] ************
fatal: [atomic-test-etcd-1] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 589, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 793, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1017, in _executor_internal_inner
    complex_args = template.template(self.basedir, complex_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 14, in root
  File "/Users/stephane/projets/perso/test-openshift-atomic/upstream/filter_plugins/oo_filters.py", line 101, in oo_collect
    retval = [FilterModule.get_attr(d, attribute) for d in data]
  File "/Users/stephane/projets/perso/test-openshift-atomic/upstream/filter_plugins/oo_filters.py", line 47, in get_attr
    ptr = ptr[attr]
KeyError: 'openshift'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/stephane/config.retry

atomic-test-etcd-1 : ok=12   changed=0    unreachable=1    failed=0
atomic-test-master-1 : ok=7    changed=0    unreachable=0    failed=0
atomic-test-node-1 : ok=14   changed=0    unreachable=0    failed=0
atomic-test-node-2 : ok=14   changed=0    unreachable=0    failed=0
localhost                  : ok=16   changed=0    unreachable=0    failed=0
```

**Comment by harobed** [comment] 2016-04-27 15:33
It's ```openshift.common.hostname``` which is empty.

**Comment by harobed** [comment] 2016-04-27 16:15
This is the version:

```
-bash-4.2# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
-bash-4.2# cat /etc/centos-release-upstream
Derived from Red Hat Enterprise Linux 7.2 (Source)
-bash-4.2# atomic host status
  TIMESTAMP (UTC)         VERSION        ID             OSNAME                 REFSPEC
* 2016-04-04 21:25:34     7.20160404     e39c28570a     centos-atomic-host     centos-atomic-host:centos-atomic-host/7/x86_64/standard

GPG: Found 1 signature on the booted deployment (*):

  Signature made Mon Apr  4 23:33:10 2016 using RSA key ID F17E745691BA8335
  Good signature from "CentOS Atomic SIG <security@centos.org>"
```

**Comment by harobed** [comment] 2016-04-29 12:00
Some news about this bug ?

**Comment by harobed** [comment] 2016-04-29 12:36
Well, to fix it in `roles/openshift_facts/tasks/main.yml`, I've commented:

```
# had to be done outside of the above because hostname isn't yet set
#- name: Gather hostnames for proxy configuration
  #openshift_facts:
    #role: common
    #local_facts:
      #http_proxy: "{{ openshift_http_proxy | default(None) }}"
      #https_proxy: "{{ openshift_https_proxy | default(None) }}"
      #no_proxy: "{{ openshift_no_proxy | default(None) }}"
      #generate_no_proxy_hosts: "{{ openshift_generate_no_proxy_hosts | default(True) }}"
      #no_proxy_internal_hostnames: "{{ hostvars | oo_select_keys(groups['oo_nodes_to_config'] 
                                                   #| union(groups['oo_masters_to_config']) 
                                                   #| union(groups['oo_etcd_to_config'] | default([]))) 
                                               #| oo_collect('openshift.common.hostname') | default([]) | join (',')
                                               #}}"

```

the rest install work with success.

**Comment by detiber** [comment] 2016-04-29 16:39
@sdodson thoughts?

**Comment by sdodson** [comment] 2016-04-29 18:40
I can't reproduce this using Ansible 1.9.4 on RHEL7, I expect it's something unique to running Ansible on a Mac. Here's the inventory I've used.

```
[OSEv3:children]
masters
nodes
etcd
[OSEv3:vars]
deployment_type=origin
containerized=true
ansible_ssh_user=centos
ansible_become=yes
[masters]
ec2-54-82-205-207.compute-1.amazonaws.com
[nodes]
ec2-54-82-205-207.compute-1.amazonaws.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
ec2-54-209-174-251.compute-1.amazonaws.com
[etcd]
ec2-54-209-110-163.compute-1.amazonaws.com
```

**Comment by sdodson** [comment] 2016-04-29 19:21
I've reproduced the issue, looking into it.

**Comment by detiber** [comment] 2016-04-29 19:38
@sdodson I seem to be hitting this as well (generally after a previously failed run)

**Comment by sdodson** [comment] 2016-04-29 19:38
Happens only when master is not also a node?

**Comment by detiber** [comment] 2016-04-29 19:39
@sdodson that could be it, I was hitting early failures on node configuration and attempting re-runs. I didn't have a chance to dig into it since I was chasing another issue

**Comment by sdodson** [comment] 2016-04-29 20:18
@harobed I'd be interested to see if the problem goes away when your master is also a node. That's currently required for various features anyway (java console, and pod autoscaling I believe).

**Comment by harobed** [comment] 2016-05-02 07:28
@sdodson the problem goes away when master is a node. It's that !

**Comment by sdodson** [comment] 2016-05-02 12:51
Ok, I'd still like to get to a root cause and a proper fix for this so lets leave this open.

**Comment by sdodson** [comment] 2016-05-02 17:25
Since this is an unsupported config dropping to P3.

**Comment by arcdigital** [comment] 2016-05-07 23:33
I'm having this same issue, however I do have my masters listed as nodes. I've removed some information from the hosts file. I'm running ansible on a RHEL 7.2 host. My repo is at version a9bf2540412983ff65ea376eb2ed0675536dd102.



```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=ec2-user
ansible_sudo=true
deployment_type=origin
openshift_master_cluster_method=native
openshift_master_cluster_hostname=<URL1>
openshift_master_cluster_public_hostname=<URL2>
openshift_master_default_subdomain=<URL3>
os_sdn_network_plugin_name=redhat/openshift-ovs-multitenant
openshift_master_session_name=<SESSION>
openshift_master_session_auth_secrets=['<SECRET1>']
openshift_master_session_encryption_secrets=['<SECRET2>']
openshift_master_portal_net=172.31.0.0/16
osm_cluster_network_cidr=10.128.0.0/14
osm_host_subnet_length=9
openshift_master_identity_providers=[{'name': 'github', 'login': 'true', 'challenge': 'false', 'kind': 'GitHubIdentityProvider', 'clientID': '<ClientID>', 'clientSecret': '<ClientSecret>', 'organizations': ['<ORG>']}]
openshift_master_named_certificates=[{"certfile": "<PATH1>", "keyfile": "<PATH2>"}]
openshift_master_public_api_url=https://<URL2>:443

# host group for masters
[masters]
ec2-4.us-west-2.compute.amazonaws.com #1
ec2-5.us-west-2.compute.amazonaws.com #2
ec2-6.us-west-2.compute.amazonaws.com #3

# host group for etcd
[etcd]
ec2-13.us-west-2.compute.amazonaws.com #1
ec2-14.us-west-2.compute.amazonaws.com #2
ec2-15.us-west-2.compute.amazonaws.com #3

# host group for nodes, includes region info
[nodes]
ec2-1.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'infra', 'zone': 'us-west-2a'}"
ec2-2.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'infra', 'zone': 'us-west-2b'}"
ec2-3.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'infra', 'zone': 'us-west-2c'}"
ec2-4.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'infra', 'zone': 'us-west-2a'}" openshift_schedulable=false
ec2-5.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'infra', 'zone': 'us-west-2b'}" openshift_schedulable=false
ec2-6.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'infra', 'zone': 'us-west-2c'}" openshift_schedulable=false
ec2-7.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'west', 'zone': 'us-west-2a'}"
ec2-8.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'west', 'zone': 'us-west-2a'}"
ec2-9.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'west', 'zone': 'us-west-2b'}"
ec2-10.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'west', 'zone': 'us-west-2b'}"
ec2-11.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'west', 'zone': 'us-west-2c'}"
ec2-12.us-west-2.compute.amazonaws.com openshift_node_labels="{'region': 'west', 'zone': 'us-west-2c'}"
```

```
ec2-1.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-2.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-3.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-4.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-5.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-6.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-7.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-8.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-9.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-10.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-11.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-12.us-west-2.compute.amazonaws.com : ok=7    changed=0    unreachable=1    failed=0
ec2-13.us-west-2.compute.amazonaws.com : ok=1    changed=0    unreachable=0    failed=0
ec2-14.us-west-2.compute.amazonaws.com : ok=1    changed=0    unreachable=0    failed=0
ec2-15.us-west-2.compute.amazonaws.com : ok=1    changed=0    unreachable=0    failed=0
localhost                  : ok=18   changed=0    unreachable=0    failed=0
```

error i'm getting for all the hosts that returned unreachable=1

```
fatal: [ec2-HOST.us-west-2.compute.amazonaws.com] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1013, in _executor_internal_inner
    complex_args = template.template(self.basedir, complex_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 14, in root
  File "/home/ec2-user/openshift-ansible/filter_plugins/oo_filters.py", line 139, in oo_collect
    retval = [FilterModule.get_attr(d, attribute) for d in data]
  File "/home/ec2-user/openshift-ansible/filter_plugins/oo_filters.py", line 49, in get_attr
    ptr = ptr[attr]
KeyError: 'openshift'
```

**Comment by abutcher** [comment] 2016-05-10 20:57
Hey @arcdigital could you confirm that you're still seeing this error with latest master branch? I added a potential fix to #1872.

**Comment by rushabh268** [comment] 2016-05-10 21:06
@abutcher Seeing the same issue with the latest master branch and specifying the master as nodes.

**Comment by abutcher** [comment] 2016-05-10 21:07
Alright, looks like we might need to set `openshift.common.hostname` there instead of in the openshift_facts role.

**Comment by harobed** [comment] 2016-05-11 08:10
> Hey @arcdigital could you confirm that you're still seeing this error with latest master branch?

Fixed here with:

* 45e5e99b1d8d155a9680f1ac00ac5fb8cfab8bec
* and specifying the master as nodes

**Comment by rushabh268** [comment] 2016-05-11 23:37
@abutcher  Do I need to specify master as a node even on a standalone install?

**Comment by sdodson** [comment] 2016-05-12 13:03
Yes.

**Comment by abutcher** [comment] 2016-05-17 13:28
I've updated #1876 to set hostname facts earlier in the playbooks so that they're available when we get to them for proxy facts. Is anyone able to give that PR a try?

**Comment by cooktheryan** [comment] 2016-05-17 13:34
@abutcher trying now

**Comment by cooktheryan** [comment] 2016-05-17 14:36
@abutcher installer works again on AWS

**Closed** 2016-05-17 17:09 UTC
Labels: kind/bug, priority/P1
