### ISSUE TITLE
show error 

### ISSUE THREAD

**Issue by zhwenh** [openshift/openshift-ansible#1687] opened 2016-03-31 07:22 UTC
one master  ，two node  ,firework is closed!
ansible 1.9.4

hosts
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true

deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# host group for masters
[masters]
master.example.com

# host group for nodes, includes region info
[nodes]
master.example.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
node1.example.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
node2.example.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}"

show this error :
TASK: [openshift_examples | Import Centos Image streams] **********************
failed: [10.1.130.14] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:00.265661", "end": "2016-03-31 14:24:58.952895", "failed": true, "failed_when_result": true, "rc": 1, "start": "2016-03-31 14:24:58.687234", "stdout_lines": [], "warnings": []}
stderr: unable to connect to a server to handle "imagestreamlists": Get https://10.1.130.14:8443/oapi: dial tcp 10.1.130.14:8443: connection refused

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/wen/config.retry

**10.1.130.14                : ok=172  changed=1    unreachable=0    failed=1**
10.1.130.15                : ok=7    changed=0    unreachable=0    failed=0
10.1.130.16                : ok=7    changed=0    unreachable=0    failed=0
localhost                  : ok=17   changed=0    unreachable=0    failed=0

**Comment by detiber** [comment] 2016-03-31 16:22
This looks like a duplicate of https://github.com/openshift/openshift-ansible/issues/1338

I'm working on trying to replicate it currently.

**Comment by zhwenh** [comment] 2016-04-04 13:24
Apr 02 23:12:08 slave673 systemd[1]: Starting Origin Master Service...
Apr 02 23:12:08 slave673 systemd[1]: origin-master.service holdoff time over, scheduling restart.
Apr 02 23:12:08 slave673 systemd[1]: origin-master.service failed.
Apr 02 23:12:08 slave673 systemd[1]: Unit origin-master.service entered failed state.
Apr 02 23:12:08 slave673 systemd[1]: origin-master.service: main process exited, code=exited, status=255/n/a
Apr 02 23:12:08 slave673 origin-master[23006]: F0402 23:12:08.130856 23006 run_components.go:357] SDN initialization failed: Error: Host network with IP: 10.1.130.0 conflicts with cluster network: 10.1.0.0/16
Apr 02 23:12:07 slave673 origin-master[23006]: I0402 23:12:07.847019 23006 common.go:77] Self IP: 10.1.130.16.
Apr 02 23:12:07 slave673 origin-master[23006]: [858.969977ms] [924ns] END
Apr 02 23:12:07 slave673 origin-master[23006]: [858.969053ms] [1.367638ms] Writing http response done (1 items)
Apr 02 23:12:07 slave673 origin-master[23006]: [857.601415ms] [28.611碌s] Self-linking done
Apr 02 23:12:07 slave673 origin-master[23006]: [857.572804ms] [857.536871ms] Listing from storage done
Apr 02 23:12:07 slave673 origin-master[23006]: [35.933碌s] [35.933碌s] About to List from storage
Apr 02 23:12:07 slave673 origin-master[23006]: I0402 23:12:07.834618 23006 trace.go:57] Trace "List /oapi/v1/imagestreams" (started 2016-04-02 23:12:06.975614435 +0800 CST):
Apr 02 23:12:07 slave673 origin-master[23006]: [761.337456ms] [610ns] END
Apr 02 23:12:07 slave673 origin-master[23006]: [761.336846ms] [1.861碌s] Decoded 1 nodes
Apr 02 23:12:07 slave673 origin-master[23006]: [761.334985ms] [761.333491ms] Decoding dir /openshift.io/imagestreams/openshift END
Apr 02 23:12:07 slave673 origin-master[23006]: [1.494碌s] [1.494碌s] Decoding dir /openshift.io/imagestreams/openshift START
 @detiber
 OpenShift Origin member
detiber commented 2 days ago
This is the relevant line:

23:12:08.130856 23006 run_components.go:357] SDN initialization failed: Error: Host network with IP: 10.1.130.0 conflicts with cluster network: 10.1.0.0/16
You will need to override the osm_cluster_network_cidr variable to use a non-conflicting network. In your inventory, you could define it as follows:

osm_cluster_network_cidr=172.16.0.0/16

**Comment by zhwenh** [comment] 2016-04-05 06:43
# **I also have the other problem, my docker 1.10 has been installed on the server, but according to the following error.**
failed: [10.1.130.16] => {"changed": true, "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: mirrors.aliyun.com\n * extras: mirrors.aliyun.com\n * updates: mirrors.aliyun.com\nResolving Dependencies\n--> Running transaction check\n---> Package docker.x86_64 0:1.9.1-25.el7.centos will be installed\n--> Processing Dependency: docker-forward-journald = 1.9.1-25.el7.centos for package: docker-1.9.1-25.el7.centos.x86_64\n--> Processing Dependency: docker-selinux >= 1.9.1-25.el7.centos for package: docker-1.9.1-25.el7.centos.x86_64\n--> Running transaction check\n---> Package docker-forward-journald.x86_64 0:1.9.1-25.el7.centos will be installed\n---> Package docker-selinux.x86_64 0:1.9.1-25.el7.centos will be installed\n--> Processing Conflict: docker-engine-1.10.3-1.el7.centos.x86_64 conflicts docker\n--> Processing Conflict: docker-engine-1.10.3-1.el7.centos.x86_64 conflicts docker-io\n--> Processing Conflict: docker-engine-selinux-1.10.3-1.el7.centos.noarch conflicts docker-selinux\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
msg: Error: docker-engine conflicts with docker-1.9.1-25.el7.centos.x86_64
Error: docker-engine-selinux conflicts with docker-selinux-1.9.1-25.el7.centos.x86_64

FATAL: all hosts have already failed -- aborting

**Comment by zhwenh** [comment] 2016-04-06 04:55
where setting openshift origin installed version? We must to setup docker >1.10 on server environment
now show this error
TASK: [docker | Downgrade docker if necessary] ******************************** 
failed: [10.1.130.14] => {"changed": true, "cmd": ["yum", "downgrade", "-y", "docker-1.8.2"], "delta": "0:00:00.359044", "end": "2016-04-06 12:56:55.767268", "rc": 1, "start": "2016-04-06 12:56:55.408224", "warnings": ["Consider using yum module rather than running yum"]}
stderr: Error: Nothing to do
stdout: Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile

epel: ftp.jaist.ac.jp No package docker-1.8.2 available.
FATAL: all hosts have already failed -- aborting

**Comment by sdodson** [comment] 2016-04-06 15:34
No released version of Origin supports docker 1.10 because kube-1.2 does
not support docker-1.10. You have to downgrade to docker-1.9

**Comment by sdodson** [comment] 2016-04-06 15:35
And both docker-1.9.1 and docker-1.8.2 are in centos extras. Please use that repo.

**Closed** 2016-04-10 15:50 UTC
