### ISSUE TITLE
3.5->3.6 Upgrade Fails on etcd migration

### ISSUE THREAD

**Issue by ashcrow** [openshift/openshift-ansible#5524] opened 2017-09-25 15:35 UTC
#### Description

Upgrade from 3.5->3.6 fails on etcd migration.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
```
ansible 2.3.1.0
  config file = /home/steve/Tech/GITHUB/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.6.2 (default, Sep 22 2017, 08:28:09) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```
* The output of `git describe`

``openshift-ansible-3.6.173.0.5-5-213-g9957b5110``

##### Steps To Reproduce
1. Install an ose 3.5 cluster
2. Upgrade control plane with ```ansible-playbook -vvv playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade_control_plane.yml```
3. See the failure error(s)

##### Expected Results
The control plane upgrades from 3.5 to 3.6.

##### Observed Results
The etcd backup fails due to splitting a ``set`` instance as if it was a string.

```
PLAY [Gate on etcd backup] ******************************************************************************************************************************************************************************************

TASK [set_fact] *****************************************************************************************************************************************************************************************************
task path: openshift-ansible/playbooks/common/openshift-cluster/upgrades/etcd/backup.yml:18                                                                                                  
ok: [localhost] => {                                 
    "ansible_facts": {                               
        "etcd_backup_completed": [                   
            "192.168.124.234"                        
        ]                                            
    },                                               
    "changed": false                                 
}                                                    

TASK [set_fact] *****************************************************************************************************************************************************************************************************
task path: openshift-ansible/playbooks/common/openshift-cluster/upgrades/etcd/backup.yml:22                                                                                                  
ok: [localhost] => {                                 
    "ansible_facts": {                               
        "etcd_backup_failed": "set()"                
    },                                               
    "changed": false                                 
}                                                    

TASK [fail] *********************************************************************************************************************************************************************************************************
task path: openshift-ansible/playbooks/common/openshift-cluster/upgrades/etcd/backup.yml:24                                                                                                  
fatal: [localhost]: FAILED! => {                     
    "changed": false,                                
    "failed": true                                   
}                                                    

MSG:                                                 

Upgrade cannot continue. The following hosts did not complete etcd backup: s,e,t,(,)
```

##### Additional Information

* 1 master and 1 node, both RHEL Atomic Host 7.4
* openshift_image_tag=v3.6.173.0.21-17
* containerized=True
* debug_level=3

**Comment by ashcrow** [comment] 2017-09-25 15:36
HEAD at the time of testing was openshift_image_tag=v3.6.173.0.21-17

**Comment by ingvagabund** [comment] 2017-09-26 13:12
I am able to reproduce it. Though, just with python3. Upgrade with Python2 works as expected.

**Comment by ashcrow** [comment] 2017-09-26 13:19
@ingvagabund that makes sense. I believe Fedora requires Python 3 to install/upgrade for at least 3.6 on. I'm happy to run my tests when a fix is available.

**Comment by ingvagabund** [comment] 2017-09-26 14:12
Duplicate of https://github.com/openshift/openshift-ansible/issues/3934

**Closed by ingvagabund** 2017-09-26 14:12 UTC
Labels: affects_3.6, kind/bug
