### ISSUE TITLE
Playbook errors during "Gather hostnames for proxy configuration"  

### ISSUE THREAD

**Issue by cooktheryan** [openshift/openshift-ansible#1898] opened 2016-05-16 17:34 UTC
I have hit this error during installs a few times.

`TASK: [openshift_facts | Gather hostnames for proxy configuration] ************ 
fatal: [scollier-master02.scott-aws.sysdeseng.com] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 589, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 793, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1017, in _executor_internal_inner
    complex_args = template.template(self.basedir, complex_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 14, in root
  File "/home/rcook/git/openshift-ansible/filter_plugins/oo_filters.py", line 139, in oo_collect
    retval = [FilterModule.get_attr(d, attribute) for d in data]
  File "/home/rcook/git/openshift-ansible/filter_plugins/oo_filters.py", line 49, in get_attr
    ptr = ptr[attr]
KeyError: 'openshift'

FATAL: all hosts have already failed -- aborting`

**Comment by abutcher** [comment] 2016-05-16 17:41
Hey @cooktheryan! Closing as a dupe of https://github.com/openshift/openshift-ansible/issues/1820 -- could you look that issue over and add a comment?

**Closed by abutcher** 2016-05-16 17:41 UTC
