### ISSUE TITLE
Failed to reconcile with RBAC file

### ISSUE THREAD

**Issue by FengyunPan** [openshift/openshift-ansible#6135] opened 2017-11-16 09:27 UTC
#### Description
TASK [template_service_broker : Reconcile with RBAC file] *********************************************************************************************************************************************************
Thursday 16 November 2017  17:15:25 +0800 (0:00:04.932)       0:11:09.874 ***** 
fatal: [master.example.com]: FAILED! => {"changed": true, "cmd": "oc process -f \"/tmp/tsb-ansible-n886G5/rbac-template.yaml\" | oc auth reconcile -f -", "delta": "0:00:01.794441", "end": "2017-11-16 17:15:27.717141", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-11-16 17:15:25.922700", "stderr": "Error: unknown shorthand flag: 'f' in -f\n\n\nUsage:\n  oc auth [options]\n\nAvailable Commands:\n  can-i       Check whether an action is allowed\n\nUse \"oc <command> --help\" for more information about a given command.\nUse \"oc options\" for a list of global command-line options (applies to all commands).", "stderr_lines": **["Error: unknown shorthand flag: 'f' in -f", "", "", "Usage:", "  oc auth [options]", "", "Available Commands:", "  can-i       Check whether an action is allowed", "", "Use \"oc <command> --help\" for more information about a given command.", "Use \"oc options\" for a list of global command-line options (applies to all commands).**"], "stdout": "", "stdout_lines": []}

##### Version
latest

##### Additional Information

```
EXTRA INFORMATION GOES HERE
```

**Comment by matthewvalimaki** [comment] 2017-11-16 23:40
I got this as well today with brand new 1.6.1 (v1.6.1+5115d708d7). Out of three masters the first (master0) failed. I assume the other two would fail two but the script stops with the first.

```
Initialization             : Complete (0:03:03)
Health Check               : Complete (0:01:09)
etcd Install               : Complete (0:01:24)
Master Install             : Complete (0:06:05)
Master Additional Install  : Complete (0:00:55)
Node Install               : Complete (0:09:06)
Hosted Install             : Complete (0:03:22)
Service Catalog Install    : In Progress (0:02:43)
        This phase can be restarted by running: playbooks/byo/openshift-cluster/service-catalog.yml



Failure summary:


  1. Hosts:    master0.example.com
     Play:     Service Catalog
     Task:     Reconcile with RBAC file
     Message:  non-zero return code
```

**Comment by matthewvalimaki** [comment] 2017-11-16 23:42
Oops this seems to be duplicate of #6086.

**Closed** 2018-01-08 02:27 UTC
