### ISSUE TITLE
openshift_master_named_certificates --> cafile is ignored

### ISSUE THREAD

**Issue by harridu** [openshift/openshift-ansible#11422] opened 2019-03-29 07:18 UTC
#### Description

The openshift_master_named_certificates --> cafile entry in the inventory file is not sent to the browser.

##### Version

```
% ansible --version
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/hdunkel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
% git describe
openshift-ansible-3.11.101-1-2-gfac2b1085
```

##### Steps To Reproduce
1. obtain a named certificate for your cluster signed by an externel ca
2. make sure that your certificate file does **not** include the whole chain, but can be found in the ca file
3. include something these lines in your inventory file
~~~
openshift_master_overwrite_named_certificates=true 
openshift_master_named_certificates=[{"certfile": "/work/okd01/okd01.cert.pem", "keyfile": "/work/okd01/okd01.key.pem", "names": ["okd01.example.com"], "cafile": "/work/okd01/okd01.ca.cert.pem" }]
~~~
4. deploy the cluster via ansible

##### Expected Results
**openssl s_client -showcerts -connect mycluster:8443** should show both certificate and ca certificate.

##### Observed Results
**openssl s_client -showcerts -connect mycluster:8443** gives me just the certificate. The ca certificate is not included.

##### Additional Information

```
Platform is Centos 7.6.
```

**Comment by vrutkovs** [comment] 2019-03-29 08:07
Dupe of https://github.com/openshift/origin/issues/10701

**Closed by vrutkovs** 2019-03-29 08:07 UTC
