### ISSUE TITLE
3.11 install: control plane pods don't come up because of invaild master-config.yaml

### ISSUE THREAD

**Issue by nex-ses** [openshift/openshift-ansible#10786] opened 2018-11-28 10:08 UTC
#### Description

On a multi-master install the deploy_cluster.yaml playbook fails when waiting for control_plane pods to come up. The control plane pods don't come because of an error in the master-config.yaml

##### Version

* Your ansible version per `ansible --version`: 2.6.5

If you're operating from a **git clone**:

* The output of `git describe`: openshift-ansible-3.11.44-1-35-g918c030

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
[abc@xxx ~]$ ansible --version
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/abc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
[abc@xxx ~]$ cd /opt/openshift-ansible/
[abc@xxx openshift-ansible]$ git describe
openshift-ansible-3.11.44-1-35-g918c030
[abc@xxx openshift-ansible]$
```

##### Steps To Reproduce
Run deploy_cluster.yml with openshift_master_identity_providers in inventory.

The key fact is that there is no ca variable defined, because it is not needed!
```
[abc@xyz ~]$ ansible all --inventory /opt/ansible/inventory/live/ --limit OSEv3 --ask-vault-pass -m debug -a "var=hostvars[inventory_hostname].openshift_master_identity_providers"
Vault password:
XYZ| SUCCESS => {
    "hostvars[inventory_hostname].openshift_master_identity_providers": [
        {
            "challenge": "false",
            "claims": {
                "email": [
                    "email"
                ],
                "id": [
                    "preferred_username"
                ],
                "name": [
                    "name"
                ],
                "preferredUsername": [
                    "preferred_username"
                ]
            },
            "client_id": "openshift",
            "client_secret": "***",
            "kind": "OpenIDIdentityProvider",
            "login": "true",
            "name": "keycloak_openid",
            "urls": {
                "authorize": "https://ABC/sso-auth/realms/live/protocol/openid-connect/auth",
                "token": "https://ABC/sso-auth/realms/live/protocol/openid-connect/token",
                "userInfo": "https://ABC/sso-auth/realms/live/protocol/openid-connect/userinfo"
            }
        }
    ]
}
```

##### Expected Results
```
The controle plane pods come up during installation.
```

##### Observed Results
```
The control plane pods don't come up during installation.

/etc/origin/master/master-config.yaml includes an invalid reference to a nonexisting ca certificate for OpenIDIdentityProvider.
```

##### Additional Information

```
This seems to be caused by the changes in https://github.com/openshift/openshift-ansible/commit/ceac075224da886598e3b483aaa9e03978a63af5#diff-54774cd1a74c81a803bc9a139d03f9d6

Especially the change in roles/lib_utils/filter_plugins/openshift_master.py, which unconditionally writes the reference to a ca file to the master-config.yml.
```

**Comment by vrutkovs** [comment] 2018-11-28 10:45
Dupe of #9988

**Closed by vrutkovs** 2018-11-28 10:45 UTC
