### ISSUE TITLE
Drain command fails on upgrade

### ISSUE THREAD

**Issue by dmytroleonenko** [openshift/openshift-ansible#5068] opened 2017-08-11 14:53 UTC
https://github.com/openshift/openshift-ansible/blob/d25db0f66934ef08c802090be6f433a7035d3fd5/playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml#L29

It looks like *drain* should be rather *adm drain*
Before fixing it was always timing out for me

**Comment by sdodson** [comment] 2017-08-11 15:02
Dupe of #4965

**Closed by sdodson** 2017-08-11 15:02 UTC
