### ISSUE TITLE
origin-node.service fails to load on Centos 7 due to bad kubeconfig file name

### ISSUE THREAD

**Issue by alongoldboim** [openshift/openshift-ansible#2234] opened 2016-07-28 16:02 UTC
@smunilla @detiber @sdodson @simon3z @dkorn 
inventory:
http://pastebin.com/UF75NiLw

ansbile log (192.168.122.7):
http://pastebin.com/zL9ZfYtP

`journalctl -lu origin-node` (192.168.122.7):
http://pastebin.com/qgSBUhZA

this file exists:
/etc/origin/node/system:node:example2.com.kubeconfig

it is being created using a bad name.

**Comment by sdodson** [comment] 2016-08-02 01:46
Dupe of #2186

**Closed by sdodson** 2016-08-02 01:46 UTC
Labels: kind/bug, priority/P1
