### ISSUE TITLE
multi-master setup : metricspublicURL set only in first master

### ISSUE THREAD

**Issue by jfcoz** [openshift/openshift-ansible#2588] opened 2016-10-12 07:00 UTC
When using byo playbook to install a multi master cluster, with metrics component, the metricspublicURL is set only on the first master master-config.yaml
##### Version

atomic-openshift-utils-3.3.28-1.git.0.762256b.el7.noarch
openshift-ansible-3.3.28-1.git.0.762256b.el7.noarch
##### Steps To Reproduce

run playbook
`- include: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml`
ansible-hosts at bottom
##### Current Result

The metricspublicURL is updated only in the first master master-config.yaml : on the web ui, metrics display only for this master.
##### Expected Result

The metricspublicURL should be updated in all masters master-config.yaml .
##### Additional Information

Inventory file :

```
[all]
master-01-priv.example.com
master-02-priv.example.com
master-03-priv.example.com
node-01-priv.example.com
node-02-priv.example.com
node-03-priv.example.com
etcd-01-priv.example.com
etcd-02-priv.example.com
etcd-03-priv.example.com
nfs-priv.example.com

[OSEv3:children]
masters
nodes
etcd
nfs

[OSEv3:vars]
ansible_ssh_user=ec2-user
ansible_become=yes

debug_level=2

product_type=openshift
deployment_type=openshift-enterprise
openshift_deployment_type=openshift-enterprise
openshift_release=v3.3

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
openshift_master_htpasswd_users={'admin': 'changed'}

osm_default_node_selector='region=primary'

osm_default_subdomain=apps.example.com

openshift_master_cluster_hostname=master.example.com
openshift_master_cluster_public_hostname=master.example.com
openshift_master_cluster_method=native
openshift_master_overwrite_named_certificates=true
os_sdn_network_plugin_name=redhat/openshift-ovs-multitenant

openshift_hosted_router_selector='region=infra'

openshift_hosted_registry_selector='region=infra'

openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_host=nfs-priv.example.com
openshift_hosted_registry_storage_nfs_options='*(rw,root_squash)'
openshift_hosted_registry_storage_nfs_directory=/exports
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=20Gi

openshift_hosted_metrics_deploy=true
openshift_hosted_metrics_storage_kind=nfs
openshift_hosted_metrics_storage_access_modes=['ReadWriteOnce']
openshift_hosted_metrics_storage_host=nfs-priv.example.com
openshift_hosted_metrics_storage_nfs_options='*(rw,root_squash)'
openshift_hosted_metrics_storage_nfs_directory=/exports
openshift_hosted_metrics_storage_volume_name=metrics
openshift_hosted_metrics_storage_volume_size=10Gi

[masters]
master-01-priv.example.com openshift_public_hostname=master-01.example.com openshift_schedulable=True
master-02-priv.example.com openshift_public_hostname=master-02.example.com openshift_schedulable=True
master-03-priv.example.com openshift_public_hostname=master-03.example.com openshift_schedulable=True

[nodes]
master-01-priv.example.com openshift_public_hostname=master-01.example.com openshift_node_labels="{'region':'infra','zone':'default'}"
master-02-priv.example.com openshift_public_hostname=master-02.example.com openshift_node_labels="{'region':'infra','zone':'default'}"
master-03-priv.example.com openshift_public_hostname=master-03.example.com openshift_node_labels="{'region':'infra','zone':'default'}"
node-01-priv.example.com openshift_public_hostname=node-01.example.com openshift_node_labels="{'region':'primary','zone':'two'}"
node-02-priv.example.com openshift_public_hostname=node-02.example.com openshift_node_labels="{'region':'primary','zone':'two'}"
node-03-priv.example.com openshift_public_hostname=node-03.example.com openshift_node_labels="{'region':'primary','zone':'one'}"

[etcd]
etcd-01-priv.example.com openshift_public_hostname=node-01.example.com
etcd-02-priv.example.com openshift_public_hostname=node-02.example.com
etcd-03-priv.example.com openshift_public_hostname=node-03.example.com

[nfs]
nfs-priv.example.com openshift_public_hostname=nfs.example.com
```

**Comment by jfcoz** [comment] 2016-10-14 13:23
@sdodson , I've try this : 
https://github.com/jfcoz/openshift-ansible/commit/121762cf6d7e21870550bfde66476a3bbbf73e61

But I got this error : 
```
TASK [openshift_metrics : Copy the admin client config(s)] *********************
task path: /home/ec2-user/openshift-ansible/roles/openshift_metrics/tasks/main.yaml:15
fatal: [master-03-priv.labo-ceph-nfs.r53.lbn.fr]: FAILED! => {
    "failed": true,
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'openshift_master_config_dir' is undefined\n\nThe error appears to have been in '/home/ec2-user/openshift-ansible/roles/openshift_metrics/tasks/main.yaml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the admin client config(s)\n  ^ here\n"
}
fatal: [master-02-priv.labo-ceph-nfs.r53.lbn.fr]: FAILED! => {
    "failed": true,
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'openshift_master_config_dir' is undefined\n\nThe error appears to have been in '/home/ec2-user/openshift-ansible/roles/openshift_metrics/tasks/main.yaml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the admin client config(s)\n  ^ here\n"
}
fatal: [master-01-priv.labo-ceph-nfs.r53.lbn.fr]: FAILED! => {
    "failed": true,
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'openshift_master_config_dir' is undefined\n\nThe error appears to have been in '/home/ec2-user/openshift-ansible/roles/openshift_metrics/tasks/main.yaml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the admin client config(s)\n  ^ here\n"
}
```
Do you have any idea of what is this error ?
Thanks

**Comment by dgoodwin** [comment] 2016-11-30 16:29
Apologies @jfcoz I can't reproduce this original issue, but I think I have a fix up for your issue in the second comment.

```
(dgoodwin@wrx ~/aws/c2) $ ansible masters -i ./hosts -a "cat /etc/origin/master/master-config.yaml" | grep metricsPublic
  metricsPublicURL: https://hawkular-metrics./hawkular/metrics
  metricsPublicURL: https://hawkular-metrics.apps.example.com/hawkular/metrics
  metricsPublicURL: https://hawkular-metrics./hawkular/metrics
```

However clearly two are wrong per #2778, switching over to that, we'll need more info before we can fix this one here though.

@sdodson @detiber I think we should drop P1 here.

**Comment by jfcoz** [comment] 2016-12-02 10:44
Yes, this is the same problem, the good metricsPublicUrl is only set on one master-config. The visibility of metrics on the web console is dependent on the master you are connecting.

**Comment by dgoodwin** [comment] 2016-12-02 12:23
Ok thanks for the info @jfcoz, closing as a dupe of#2778.

**Closed by dgoodwin** 2016-12-02 12:23 UTC
Labels: backport/3.3, kind/bug, priority/P2
