### ISSUE TITLE
TASK: [openshift_node_certificates | Retrieve the node config tarballs from the master] *** - broken for me

### ISSUE THREAD

**Issue by LutzLange** [openshift/openshift-ansible#1956] opened 2016-05-27 13:43 UTC
This does not work for me as my systems can't be accessed with root directly.

TASK: [openshift_node_certificates | Retrieve the node config tarballs from the master] *** 
fatal: [tnode2 -> tmaster] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 589, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 793, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1040, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/action_plugins/fetch.py", line 147, in run
    f = open(dest, 'w')
IOError: [Errno 13] Permission denied: u'/tmp/openshift-ansible-31JY5gq/node-tnode2.tgz'

fatal: [tnode1 -> tmaster] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 589, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 793, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1040, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/action_plugins/fetch.py", line 147, in run
    f = open(dest, 'w')
IOError: [Errno 13] Permission denied: u'/tmp/openshift-ansible-1u2nAXE/node-tnode1.tgz'

fatal: [tmaster -> tmaster] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 589, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 793, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1040, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/action_plugins/fetch.py", line 147, in run
    f = open(dest, 'w')
IOError: [Errno 13] Permission denied: u'/tmp/openshift-ansible-nei6mdM/node-tmaster.tgz'

fatal: [tnode3 -> tmaster] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 589, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 793, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1040, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/action_plugins/fetch.py", line 147, in run
    f = open(dest, 'w')
IOError: [Errno 13] Permission denied: u'/tmp/openshift-ansible-jt9CI8m/node-tnode3.tgz'

FATAL: all hosts have already failed -- aborting

**Comment by LutzLange** [comment] 2016-05-27 14:14
It might could be that private tmp is a problem here.
see : /usr/lib/tmpfiles.d/tmp.conf

**Comment by detiber** [comment] 2016-05-27 14:57
@LutzLange it may be more subtle than that...  I think what is happening is that it is attempting to use the same user for both the localhost and remote actions, when it should be using the local user for the local actions and the specified user for remote actions...  will try to replicate and debug further today.

**Comment by LutzLange** [comment] 2016-05-27 15:29
I have a normal user and sudo to root with the same normal user on all machines. Do you want to test on my infrastructure? Do you need / want my inventory?

As a root user where would these files be?

/home/llange/.ansible/tmp/
or 
/tmp/tmp*/

**Comment by detiber** [comment] 2016-05-27 15:42
@LutzLange the inventory will definitely help. I might take you up  on the infrastructure, but I should be able to replicate it relatively easily on my end.

As far as the location of the files, we call `mktemp -d /tmp/openshift-ansible-XXXXXXX`

**Comment by detiber** [comment] 2016-05-27 16:17
@LutzLange I have a reproducer now, so no need for the inventory or other data.

**Comment by detiber** [comment] 2016-05-27 21:32
@LutzLange it looks like we didn't test for the non-sudo local host and sudo remote host for a refactoring change for certificate handling that landed. 

We're hitting a bug with ansible 1.9, and we'll need to get the offending change reverted until after we ship and require ansible 2.0+. I am planning on working on reverting the problematic changes over the weekend.

@abutcher heads up

**Comment by LutzLange** [comment] 2016-05-28 05:32
Is ansible 2.0 currently a working option? I could switch to that.

**Closed** 2016-05-30 22:47 UTC
Labels: kind/bug, priority/P0

**Comment by detiber** [comment] 2016-05-31 15:38
@LutzLange ansible 2.0 *should* work, but it hasn't undergone full regression testing yet.
