### ISSUE TITLE
prerequisites.yml fails on Gather Cluster Facts 

### ISSUE THREAD

**Issue by vremenar** [openshift/openshift-ansible#11506] opened 2019-04-16 19:16 UTC
#### Description

Provide a brief description of your issue here. For example:

> prerequisites.yml fails on Gather Cluster Facts with error: 
>.fatal: [lab-os-master01.lab.local]: FAILED! => {"changed": false, "module_stderr":  "AttributeError(\"'NoneType' object has no attribute 'startswith'\",)\nKeyError('ansible_os_family',)\nTraceback (most recent call last):\n  File \"<stdin>\", line 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1682, in <module>\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1669, in main\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1335, in __init__\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1365, in generate_facts\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1504, in init_provider_facts\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1443, in guess_host_provider\nKeyError: 'ansible_product_name'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

##### Version

Please put the following version information in the code block
indicated below.

```
ansible 2.7.10
  config file = /opt/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

openshift-ansible-3.9.77-1-8-gc75cd00
```

##### Steps To Reproduce
1. Just running prerequisites checker

##### Expected Results

Command:
```
ansible-playbook -i openshift_inventory playbooks/prerequisites.yml
```

##### Observed Results

The error: 
```
fatal: [lab-os-master01.lab.local]: FAILED! => {"changed": false, "module_stderr": "AttributeError(\"'NoneType' object has no attribute 'startswith'\",)\nKeyError('ansible_os_family',)\nTraceback (most recent call last):\n  File \"<stdin>\", line 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1682, in <module>\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1669, in main\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1335, in __init__\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1365, in generate_facts\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1504, in init_provider_facts\n  File \"/tmp/ansible_openshift_facts_payload_Avkw9Z/__main__.py\", line 1443, in guess_host_provider\nKeyError: 'ansible_product_name'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: CentOS Linux release 7.6.1810 (Core)

Outputs from gather facts and prerequisites available here: https://gist.github.com/vremenar/f851b99d755737f3c0d237d528eaa0f9

**Comment by jukito** [comment] 2019-04-16 20:16
Looking your problem....
https://github.com/openshift/openshift-ansible/issues/11497

You need to downgrade your Ansible version. Test it, please.

**Comment by vremenar** [comment] 2019-04-16 20:48
That helped. Thank you.

**Comment by vrutkovs** [comment] 2019-04-17 07:21
Dupe of #11497

**Closed by vrutkovs** 2019-04-17 07:21 UTC
