### ISSUE TITLE
Message:  |failed expects to merge two dicts

### ISSUE THREAD

**Issue by dsaha-84** [openshift/openshift-ansible#9543] opened 2018-08-11 07:11 UTC
#### Description

Provide a brief description of your issue here. For example:

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: NAME="CentOS Linux"
VERSION="7 (Core)"

* Your inventory file (especially any non-standard configuration parameters)
hosts(ansible inventory file)
[OSEv3:children]
masters
etcd
nodes

[OSEv3:vars]
ansible_ssh_user=centos
ansible_sudo=true
ansible_become=true

deployment_type=origin
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_install_examples=true

openshift_docker_options='--selinux-enabled --insecure-registry 172.30.0.0/16'
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
openshift_disable_check=disk_availability,docker_storage,memory_availability

[masters]
master.example.com

[etcd]
master.example.com

[nodes]
master.example.com openshift_node_labels="{'region':'infra','zone':'east'}" openshift_schedulable=true
node1.example.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
node2.example.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}"

* Sample code, etc

```
EXTRA INFORMATION GOES HERE

Hello,
I am using AWS Centos7 ami machine with enough memory and storage for openshift run.
All my instances (master, node1, node2) are all AWS Centos7 instances.
Whicle I ran any byo/config.yml  from any branch, I am getting this error:

===============================================================
PLAY [Configure masters] *******



TASK [openshift_hosted_facts : Set hosted facts] *************************************************************
fatal: [master.example.com]: FAILED! => {"msg": "|failed expects to merge two dicts"}

NO MORE HOSTS LEFT *******************************************************************************************
        to retry, use: --limit @/home/centos/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP ***************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0
master.example.com         : ok=242  changed=23   unreachable=0    failed=1
node1.example.com          : ok=112  changed=7    unreachable=0    failed=0
node2.example.com          : ok=112  changed=7    unreachable=0    failed=0



Failure summary:


  1. Hosts:    master.example.com
     Play:     Configure masters
     Task:     Set hosted facts
     Message:  |failed expects to merge two dicts
==================================================================

Please help me out.
Thanks Much
D.Saha
dsaha.cse@gmail.com
```

**Comment by vrutkovs** [comment] 2018-08-11 07:54
Duplicate of #7596

**Closed by vrutkovs** 2018-08-11 07:54 UTC
