### ISSUE TITLE
Install NetworkManager automatically

### ISSUE THREAD

**Issue by dvohra** [openshift/openshift-ansible#2272] opened 2016-08-08 23:40 UTC
While Docker, etcd and HAProxy get installed automatically shouldn't NetworkManager get installed automatically too?

The following commands are required to be run on Centos or RedHat.
```
sudo yum install NetworkManager
sudo systemctl start NetworkManager
sudo systemctl enable NetworkManager
sudo systemctl status NetworkManager
```

**Comment by dvohra** [comment] 2016-08-09 13:07
Thanks for the correction.

**Comment by sdodson** [comment] 2016-08-09 13:17
Dupe of #1807

**Closed by sdodson** 2016-08-09 13:17 UTC
