### ISSUE TITLE
PTY allocation request failed on channel 0

### ISSUE THREAD

**Issue by jprovaznik** [openshift/openshift-ansible#1779] opened 2016-04-20 15:35 UTC
openshift-ansible fails when running on atomic host (containerized deployment). During openshift-ansible run selinux setting on master&openshift nodes is changed which causes that any ssh connection to master/openshift nodes fails with error:

$ ssh centos@172.24.4.204
PTY allocation request failed on channel 0

In permissive mode this AVC is logged on the master node:
Apr 20 15:27:06 atomic2-origin-master-0.example.com kernel: type=1400 audit(1461166026.440:42): avc:  denied  { open } for  pid=3978 comm="sshd" path="/dev/pts/ptmx" dev="devpts" ino=2 scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:devpts_t:s0 tclass=chr_file

used env:
- centos atomic host
- openshift-ansible master branch (last commit afff74593f6de2492e3ed1cbe63f68a2dfb732f3)

**Comment by jprovaznik** [comment] 2016-04-20 15:41
[ansible.11706.txt](https://github.com/openshift/openshift-ansible/files/228266/ansible.11706.txt)

**Comment by sdodson** [comment] 2016-04-20 15:42
@dgoodwin relevant to your interests (mine too)

**Comment by sdodson** [comment] 2016-04-20 15:43
This works as root, probably related to our /dev being mounted into the container but we haven't isolated why this is happening.

**Comment by dgoodwin** [comment] 2016-04-20 15:45
I have been testing quite a bit last few days with that /dev into node container mount removed, I haven't hit this once since. Very likely that is the cause.

**Comment by jprovaznik** [comment] 2016-04-20 15:46
It might be this is caused by a change done in last 12 days (yes, still quite a big timeframe) - I didn't hit this when using 12 old code

**Comment by sdodson** [comment] 2016-04-20 15:50
I added -v /dev:/dev in 105cd9b77f3d6b2e8875b2cd5f323463b3f04059 so installs after March 22nd should have this problem

**Comment by gordillo-ramon** [comment] 2016-04-25 01:31
Reason explained: https://github.com/kubernetes/kubernetes/issues/17576

**Comment by sdodson** [comment] 2016-04-25 12:38
The docker fix for this came from https://github.com/docker/docker/pull/16639 so any version of docker-1.10 as well as a forthcoming update to docker-1.9.1 in RHEL7/Centos7 will address this.

**Comment by gordillo-ramon** [comment] 2016-04-25 12:46
From [(https://github.com/docker/docker/commit/91876563052a1d84902e365cbe8b9eaf96846e91)], I see no 1.9.1 version supported. AFAIK, RHEL7/Centos7 already has this version in the last update. I am using Centos Atomic Host 7, facing the issue. The only workaround that worked for me was using root instead of another user + sudo.

**Comment by sdodson** [comment] 2016-04-25 12:52
@gordillo-ramon The patched version docker-1.9.1 hasn't yet made it to RHEL7/Centos7. I'll work on adding a build including this fix to the origin-next repo later today. 

If you don't rely on storage plugins? If not then you can merge #1789 as a workaround.
git pull https://github.com/sdodson/openshift-ansible bz1329326

**Comment by sdodson** [comment] 2016-04-26 21:16
docker-1.9.1-31.origin.1.el7 should be available in the COPR repo with the patches necessary to fix this. Please try it and let me know if it doesn't resolve the issue for you, thanks. I'm not sure how to update atomic host with a particular rpm so this obviously won't work for atomic host.

**Comment by dgoodwin** [comment] 2016-04-27 10:55
FWIW If the rpm matches what CentOS atomic host actually uses it should be possible to test it with atomic-pkglayer.

**Comment by sdodson** [comment] 2016-05-18 17:13
This is fixed by upgrading to docker-1.9.1-40 or atomic host 7.2.4

**Closed by sdodson** 2016-05-18 17:13 UTC
Labels: kind/bug, priority/P1
