### ISSUE TITLE
openshift pulling image error

### ISSUE THREAD

**Issue by alex8158** [openshift/openshift-ansible#11668] opened 2019-06-06 05:10 UTC
i have installed 3.11 recently. but in these weeks, I cannot deploy any project which I succeeded deployed before, such as php , pathon. the error is:

pulling image error : unknown: unable to pull manifest from docker.io/openshift/wildfly-130-centos7:latest: Get https://registry-1.docker.io/v2/:  x509: certificate is valid for *.router.default.svc.cluster.local, router.default.svc.cluster.local, not registry-1.docker.io
--
  | error: build error: unable to get docker-registry.default.svc:5000/openshift/wildfly@sha256:895e0a6c732f8244ce75b376651155fdef12311df0d940ce111756ef43aa2bfc

pulling image error : unknown: unable to pull manifest from docker.io/centos/php-71-centos7:latest: Get https://registry-1.docker.io/v2/:  x509: certificate is valid for *.router.default.svc.cluster.local, router.default.svc.cluster.local, not registry-1.docker.io
error: build error: unable to get docker-registry.default.svc:5000/openshift/php@sha256:ed72ebcd21241c31fcc9041c802c337e7d41301fea90e76ff83e28bbd5ca271d

also I create jekins ,the error is: 

--> Scaling jenkins-1 to 1
--
  | error: update acceptor rejected jenkins-1: pods for rc 'ci/jenkins-1' took longer than 600 seconds to become available

**Comment by vrutkovs** [comment] 2019-06-06 07:01
Dupe of #11667

**Closed by vrutkovs** 2019-06-06 07:01 UTC

**Comment by remkohdev** [comment] 2019-10-03 20:37
Same here, seems a simple timeout in the installation process during pulling of images. Rerunning a Deploy of the same service, solved the issue. I assume cause previous images being cached already.
