### ISSUE TITLE
Recursive loop detected in template string: {{ openshift_logging_elasticsearch_pvc_dynamic | default(False) }}

### ISSUE THREAD

**Issue by DougWagner** [openshift/openshift-ansible#11884] opened 2019-09-06 19:33 UTC
#### Description

A recursive loop is detected when trying to deploy logging on a brand new OKD 3.11 install when using `openshift_logging_elasticsearch_storage_type=pvc` and `openshift_logging_es_cluster_size=3`, causing the deploy to fail.

##### Version
```
[dwagner@<host-redacted> openshift-ansible]$ ansible --version
ansible 2.8.2
  config file = /home/dwagner/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/dwagner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[dwagner@<host-redacted> openshift-ansible]$ git describe
openshift-ansible-3.11.143-1-2-g64b5455
```

##### Steps To Reproduce
1. Deploy a new OKD cluster and configure persistent storage
2. Run the deploy logging playbook with `openshift_logging_elasticsearch_storage_type=pvc` set in hosts file.

##### Expected Results
The playbook to complete and logging to deploy with PVs claimed for logging.

##### Observed Results
The installer fails at the `Creating ES storage template - static` task and gives the following error message:

[Error message gist since it's long](https://gist.github.com/DougWagner/5048f01ca437f77f3ca78a40f87179ce)

I did some searching for `openshift_logging_elasticsearch_pvc_dynamic` and discovered that commenting out line 129 in `roles/openshift_logging/tasks/install_logging.yaml` (`openshift_logging_elasticsearch_pvc_dynamic: "{{ openshift_logging_es_pvc_dynamic }}"`) added in commit f522686a420fa95b680973f1be32feca977a3fb7 will eliminate the recursive loop and enable the logging deploy to complete and make PVCs for elasticsearch. 

##### Additional Information

OS: CentOS 7 (1810)

Inventory file:

```
[masters]
<redacted>

[etcd]
<redacted>
<redacted>
<redacted>

[nodes]
<redacted> openshift_node_group_name="node-config-master"
<redacted> openshift_node_group_name="node-config-compute"
<redacted> openshift_node_group_name="node-config-compute"
<redacted> openshift_node_group_name="node-config-infra"
<redacted> openshift_node_group_name="node-config-infra"

[lb]
<redacted>

[OSEv3:children]
masters
nodes
etcd
lb

[OSEv3:vars]
ansible_user=root
openshift_deployment_type=origin
openshift_master_default_subdomain=<redacted>
openshift_master_cluster_hostname=<redacted>
debug_level=2

# LDAP identity provider
openshift_master_identity_providers=[<redacted>]
openshift_master_ldap_ca_file=/etc/ssl/certs/ca-bundle.crt

# public hostname
openshift_master_cluster_public_hostname=<redacted>

# login token lasts 14 days instad of the default 24 hours
openshift_master_access_token_max_seconds=1209600

# router cert
openshift_hosted_router_certificate={<redacted>}

# metrics deployment
openshift_metrics_install_metrics=true
openshift_metrics_duration=30
openshift_metrics_cassandra_pvc_size=200Gi
openshift_metrics_cassandra_storage_type=pv
openshift_metrics_hawkular_cert="<redacted>"
openshift_metrics_hawkular_key="<redacted>"
openshift_metrics_hawkular_ca="<redacted>"
openshift_metrics_hawkular_hostname="<redacted>"

# logging deployment
openshift_logging_install_logging=true
openshift_logging_curator_default_days=60
openshift_logging_es_nodeselector={"node-role.kubernetes.io/master":"true"}
openshift_logging_es_number_of_replicas=2
openshift_logging_es_number_of_shards=3
openshift_logging_es_pvc_size=400Gi
openshift_logging_elasticsearch_storage_type=pvc
openshift_logging_kibana_hostname=<redacted>
openshift_logging_kibana_cert="<redacted>"
openshift_logging_kibana_key="<redacted>"
openshift_logging_kibana_ca="<redacted>"
openshift_logging_es_cluster_size=3

# master cert
openshift_master_overwrite_named_certificates=true
openshift_master_named_certificates=[{<redacted>}]

# additional credentials for operator framework
openshift_additional_registry_credentials=[{'host':'registry.connect.redhat.com','user':'<redacted>','password':'<redacted>','test_image':'mongodb/enterprise-operator:0.3.2'}]
```

**Comment by rmetzler** [comment] 2019-09-18 14:01
I have the same problem with the RHEL `openshift-ansible.noarch : Openshift and Atomic Enterprise Ansible` package.

some more context:

```
[...] Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ openshift_logging_elasticsearch_pvc_dynamic | default(False) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: recursive loop detected in template string: {{ openshift_logging_elasticsearch_pvc_dynamic | default(False) }}
               
               The error appears to have been in '/usr/share/ansible/openshift-ansible/roles/openshift_logging_elasticsearch/tasks/main.yaml': line 395, column 5, but may
               be elsewhere in the file depending on the exact syntax problem.
               
               The offending line appears to be:
               
                 # storageclasses with the storageClassName set to "" in pvc.j2
                 - name: Creating ES storage template - static
                   ^ here
```

```
yum info openshift-ansible                                                                       
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Installed Packages
Name        : openshift-ansible
Arch        : noarch
Version     : 3.11.141
Release     : 1.git.0.a7e91cd.el7
Size        : 49 k
Repo        : installed
From repo   : rhel-7-server-ose-3.11-rpms
Summary     : Openshift and Atomic Enterprise Ansible
URL         : https://github.com/openshift/openshift-ansible
License     : ASL 2.0
Description : Openshift and Atomic Enterprise Ansible
            : 
            : This repo contains Ansible code and playbooks
            : for Openshift and Atomic Enterprise.
```

At first the inventory hadn't had this variable set. Then I tried this line, but it still fails:

```
openshift_logging_elasticsearch_pvc_dynamic=false
```

**Comment by rhdojun** [comment] 2019-10-08 16:43
Also having this error, with 3.11.141 and nfs storage. We saw that at some point there were the Cassandra files in the logging mount volume. We suspect it binds the wrong pvs and pvcs at least for some time and tried giving other volume sizes. Still bad result, although logging dir stays empty.

**Comment by rhdojun** [comment] 2019-10-09 06:19
In the [docs](https://docs.openshift.com/container-platform/3.11/install/configuring_inventory_file.html#advanced-installation-logging-storage) we found a part where a similar variable `openshift_logging_es_pvc_dynamic` is *required* to be set.

It is confusing to read though. It seems there are three types of storage possible and only in one of them it explains how to set the variable for this type. Does it mean for the other types it's to be set to `false`? If I set it to `false` will it still provide the NFS PV by itself?

We will experiment this now, but each run takes ~30 minutes, so it's quite painful. Would be great if a dev could review this and maybe trigger an update to the documentation.

**Comment by rhdojun** [comment] 2019-10-09 08:03
Experiment failed, didn't work by setting this variable to false. Maybe setting it to true would also help, but at customer site we don't have the time. We will likely go back to an older 3.11.x package next where it worked without setting this.

**Comment by rhdojun** [comment] 2019-10-09 09:58
Openshift `3.11.123` simply succeeds without further changes to the inventory file

**Comment by as0bu** [comment] 2019-10-11 03:24
I'm seeing this same issue with `3.11.146` as well with NFS storage.

**Comment by as0bu** [comment] 2019-10-11 03:41
Just tried @DougWagner's suggestion and that worked for me.

```bash
$ oc get pvc --all-namespaces
NAMESPACE           NAME             STATUS    VOLUME            CAPACITY   ACCESS MODES   STORAGECLASS   AGE
default             registry-claim   Bound     registry-volume   10Gi       RWX                           3h
openshift-logging   logging-es-0     Bound     logging-volume    10Gi       RWO                           10m
```

**Comment by gandhiano** [comment] 2019-10-25 08:56
I can confirm that setting `openshift_logging_es_pvc_dynamic` to `true` and explicitly defining `openshift_logging_elasticsearch_storage_type` did solve this issue. 

Additionally, we also define some other vars, like `openshift_logging_es_pvc_size` and `openshift_logging_es_pvc_storage_class_name`. Maybe this helps also for those who want to set to `false`.

**Comment by itewk** [comment] 2019-12-16 16:58
I am seeing this to useing the `release-3.11` playbooks.

**Comment by itewk** [comment] 2019-12-16 18:07
in my case it was because i had `openshift_logging_es_ops_pvc_dynamic` in my inventory twice but didn't have `openshift_logging_es_pvc_dynamic` at all. In other words. Copy paste error.

Though you would think if you didn't supply `openshift_logging_es_pvc_dynamic` you would get a better error message then recursion...

**Comment by jcantrill** [comment] 2020-07-08 16:55
Closing issue as resolved.  Please re-open if it needs to still be addressed

**Closed by jcantrill** 2020-07-08 16:55 UTC
Labels: lifecycle/rotten
