### ISSUE TITLE
Unable to deploy to GCE

### ISSUE THREAD

**Issue by gnufied** [openshift/openshift-ansible#2676] opened 2016-10-27 13:32 UTC
##### Version

```
openshift-ansible-3.4.12-1-10-g1f28e81
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Steps To Reproduce
1. Setup service account and keys and everything as per documention
2. Run `bin/cluster create gce foobar-cluster`
##### Current Result

The master node is started correctly but then deployment fails with following error:

```
ok: [localhost] => (item={u'status': u'RUNNING', u'network':
u'default', u'zone': u'us-east1-c', u'tags': [u'created-by-foouser',
u'environment-dev', u'clusterid-foouser-openshift', u'host-type-
master', u'sub-host-type-default'], u'image': u'centos-7-v20160921',
u'disks': [u'foouser-
openshift-master-5bb30'], u'name': u'foouser-openshift-master-5bb30',
u'public_ip': u'104.196.208.43', u'private_ip': u'10.240.0.6',
u'machine_type': u'n1-standard-1', u'metadata': {u'startup-script':
u'#!/bin/bash\necho "Defaults:foouser !requiretty" > /etc/sudoers.d/99-
foouser\n'}}
)
 ____________________________
< TASK [Wait for user setup] >
FAILED - RETRYING: TASK: Wait for user setup (3 retries left).
FAILED - RETRYING: TASK: Wait for user setup (2 retries left).
FAILED - RETRYING: TASK: Wait for user setup (1 retries left).
failed: [localhost] (item={u'status': u'RUNNING', u'network':
u'default', u'zone': u'us-east1-c', u'tags': [u'created-by-foouser',
u'environment-dev', u'clusterid-foouser-openshift', u'host-type-
master', u'sub-host-type-default'], u'image': u'centos-7-v20160921',
u'disks': [u'foouser
-openshift-master-5bb30'], u'name': u'foouser-openshift-master-5bb30',
u'public_ip': u'104.196.208.43', u'private_ip': u'10.240.0.6',
u'machine_type': u'n1-standard-1', u'metadata': {u'startup-script':
u'#!/bin/bash\necho "Defaults:foouser !requiretty" > /etc/sudoers.d/99-
foouser\n'}
}) => {"changed": true, "cmd": ["ssh", "-o",
"StrictHostKeyChecking=no", "-o", "PasswordAuthentication=no", "-o",
"ConnectTimeout=10", "-o", "UserKnownHostsFile=/dev/null", "foouser@104
.196.208.43", "echo", "foouser", "user", "is", "setup"], "delta":
"0:00:00.357068", "end": "2016-10
-24 23:42:44.678491", "failed": true, "item": {"disks": ["foouser-
openshift-master-5bb30"], "image": "centos-7-v20160921",
"machine_type": "n1-standard-1", "metadata": {"startup-script":
"#!/bin/bash\necho \"Defaults:foouser !requiretty\" >
/etc/sudoers.d/99-foouser\n"}, "name": "hek
umar-openshift-master-5bb30", "network": "default", "private_ip":
"10.240.0.6", "public_ip": "104.196.208.43", "status": "RUNNING",
"tags": ["created-by-foouser", "environment-dev", "clusterid-foouser-
openshift", "host-type-master", "sub-host-type-default"], "zone": "us-
east1-c"}, "r
c": 255, "start": "2016-10-24 23:42:44.321423", "stderr": "Warning:
Permanently added '104.196.208.43' (ECDSA) to the list of known
hosts.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic).", 
"stdout": "", "stdout_lines": [], "warnings": []}
 ____________________

```
##### Expected Result

The deployment should have succeeded.
##### Additional Information

I am running this from Fedora24 machine. Since the error appears to be related to SSH, I also tried using:

```
ANSIBLE_SSH_ARGS="-i ~/.ssh/google_compute_engine -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=600s" bin/cluster create gce foobar-cluster
```

Those keys(saved in `~/.ssh/google_compute`) were generated by `gcloud` as part of GCE setup process. They are different from my personal public and private keys saved in `~/.ssh/id_rsa` etc.

**Comment by gnufied** [comment] 2016-10-27 13:38
Since openshift-ansible scripts are able to create and start master node properly, I figured my gcloud setup isn't borked and is working. But if anyone has better idea - please let me know.

**Comment by jshearer** [comment] 2017-05-04 00:02
Any news on this? I'm having the same issue still...

**Comment by highlandrulz** [comment] 2017-05-17 19:09
Having exactly the same issue. Did anybody make any progress on this?

**Comment by ephillipe** [comment] 2017-07-16 17:44
I having same issue. 
The problem is i cannot know how pass the -i parameter to this SSH command.

I try use this var env without success:
`export ANSIBLE_SSH_ARGS = '-o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=30s -i /home/erick/desenvolvimento/panel/.gce/service-account/openshift/eventflit-xxxxxxxxxxx.pem'`

**Comment by michaelgugino** [comment] 2017-09-12 21:56
The affected code path has been removed.

Closing this issue because it is now invalid.

**Closed by michaelgugino** 2017-09-12 21:56 UTC
