### ISSUE TITLE
No package matching 'origin-node-3.11

### ISSUE THREAD

**Issue by magick93** [openshift/openshift-ansible#10401] opened 2018-10-14 03:12 UTC
#### Description

Attempt to install okd 3.11.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/anton/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

If you're operating from a **git clone**:

* The output of `git describe`

`v3.11.0`

##### Steps To Reproduce
1. pull ` v3.11.0 ` tag from this repo
2. try to install using this inventory - https://gist.github.com/magick93/c4f19639166f2b619c1c7db7e4f87348

##### Expected Results
Expected Okd v3.11.0 to install.

##### Observed Results

```
Play:     Configure nodes
     Task:     Install node, clients, and conntrack packages
     Message:  No package matching 'origin-node-3.11' found available, installed or updated
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by nagonzalez** [comment] 2018-10-14 18:35
Check out this thread:
https://github.com/openshift/openshift-ansible/issues/9875

**Comment by DanyC97** [comment] 2018-10-15 10:02
@vrutkovs let's close this issue, i've repeated few times already here and on dev mailer that is on my top priority list to get the rpms out.

I hope people will be patient while i'm working through, it doesn't help anyone if we keep open new issues with same problem.

I am doing my best to keep everyone up to date and for that the dev/ user mailer is the place to be.


also fyi @magick93 ansible `v2.7` is not supported nor working with anyone of the releases, just a heads up.

**Comment by vrutkovs** [comment] 2018-10-15 10:09
Duplicate of #9875

**Closed by vrutkovs** 2018-10-15 10:09 UTC

**Comment by abhiroopghatak** [comment] 2019-01-30 08:15
No package http://rpms.svc.ci.openshift.org:8080/openshift-origin-v3.11/ available.
Error: Nothing to do
..Please verify before post
