### ISSUE TITLE
node could not register

### ISSUE THREAD

**Issue by pstinghua** [openshift/openshift-ansible#538] opened 2015-08-31 11:14 UTC
```
TASK: [openshift_manage_node | Wait for Node Registration] ********************
failed: [m1.cloud.sanjiang.info] => (item=m1.cloud.sanjiang.info) => {"attempts": 10, "changed": true, "cmd": ["oc", "get", "node", "m1.cloud.sanjiang.info"], "delta": "0:00:00.315586", "end": "2015-08-31 19:06:31.410454", "failed": true, "item": "m1.cloud.sanjiang.info", "rc": 1, "start": "2015-08-31 19:06:31.094868", "warnings": []}
stderr: Error from server: node "m1.cloud.sanjiang.info" not found
msg: Task failed as maximum retries was encountered
failed: [m1.cloud.sanjiang.info] => (item=m2.cloud.sanjiang.info) => {"attempts": 10, "changed": true, "cmd": ["oc", "get", "node", "m2.cloud.sanjiang.info"], "delta": "0:00:00.305844", "end": "2015-08-31 19:07:27.312925", "failed": true, "item": "m2.cloud.sanjiang.info", "rc": 1, "start": "2015-08-31 19:07:27.007081", "warnings": []}
stderr: Error from server: node "m2.cloud.sanjiang.info" not found
msg: Task failed as maximum retries was encountered
failed: [m1.cloud.sanjiang.info] => (item=m3.cloud.sanjiang.info) => {"attempts": 10, "changed": true, "cmd": ["oc", "get", "node", "m3.cloud.sanjiang.info"], "delta": "0:00:00.356756", "end": "2015-08-31 19:08:23.774215", "failed": true, "item": "m3.cloud.sanjiang.info", "rc": 1, "start": "2015-08-31 19:08:23.417459", "warnings": []}
stderr: Error from server: node "m3.cloud.sanjiang.info" not found
msg: Task failed as maximum retries was encountered
failed: [m1.cloud.sanjiang.info] => (item=n1.cloud.sanjiang.info) => {"attempts": 10, "changed": true, "cmd": ["oc", "get", "node", "n1.cloud.sanjiang.info"], "delta": "0:00:00.314444", "end": "2015-08-31 19:09:19.667453", "failed": true, "item": "n1.cloud.sanjiang.info", "rc": 1, "start": "2015-08-31 19:09:19.353009", "warnings": []}
stderr: Error from server: node "n1.cloud.sanjiang.info" not found
msg: Task failed as maximum retries was encountered
failed: [m1.cloud.sanjiang.info] => (item=n2.cloud.sanjiang.info) => {"attempts": 10, "changed": true, "cmd": ["oc", "get", "node", "n2.cloud.sanjiang.info"], "delta": "0:00:00.285436", "end": "2015-08-31 19:10:15.528383", "failed": true, "item": "n2.cloud.sanjiang.info", "rc": 1, "start": "2015-08-31 19:10:15.242947", "warnings": []}
stderr: Error from server: node "n2.cloud.sanjiang.info" not found
msg: Task failed as maximum retries was encountered
failed: [m1.cloud.sanjiang.info] => (item=n3.cloud.sanjiang.info) => {"attempts": 10, "changed": true, "cmd": ["oc", "get", "node", "n3.cloud.sanjiang.info"], "delta": "0:00:00.330001", "end": "2015-08-31 19:11:11.227746", "failed": true, "item": "n3.cloud.sanjiang.info", "rc": 1, "start": "2015-08-31 19:11:10.897745", "warnings": []}
stderr: Error from server: node "n3.cloud.sanjiang.info" not found
msg: Task failed as maximum retries was encountered
failed: [m1.cloud.sanjiang.info] => (item=n4.cloud.sanjiang.info) => {"attempts": 10, "changed": true, "cmd": ["oc", "get", "node", "n4.cloud.sanjiang.info"], "delta": "0:00:00.337508", "end": "2015-08-31 19:12:07.289400", "failed": true, "item": "n4.cloud.sanjiang.info", "rc": 1, "start": "2015-08-31 19:12:06.951892", "warnings": []}
stderr: Error from server: node "n4.cloud.sanjiang.info" not found
msg: Task failed as maximum retries was encountered
failed: [m1.cloud.sanjiang.info] => (item=n5.cloud.sanjiang.info) => {"attempts": 10, "changed": true, "cmd": ["oc", "get", "node", "n5.cloud.sanjiang.info"], "delta": "0:00:00.302550", "end": "2015-08-31 19:13:03.138179", "failed": true, "item": "n5.cloud.sanjiang.info", "rc": 1, "start": "2015-08-31 19:13:02.835629", "warnings": []}
stderr: Error from server: node "n5.cloud.sanjiang.info" not found
msg: Task failed as maximum retries was encountered
```

**Comment by pstinghua** [comment] 2015-08-31 11:15
here is my inventory file:
```
# This is an example of a bring your own (byo) host inventory

# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a
# password. If using ssh key based auth, then the key should be managed by an
# ssh agent.
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_sudo must be set to true and the
# user must be configured for passwordless sudo
#ansible_sudo=true

# deployment type valid values are origin, online and enterprise
deployment_type=origin

# Pre-release registry URL
#oreg_url=rcm-img-docker01.build.eng.bos.redhat.com:5001/openshift3/ose-${component}:${version}

# Pre-release Dev puddle repo
#openshift_additional_repos=[{'id': 'ose-devel', 'name': 'ose-devel', 'baseurl': 'http://buildvm-devops.usersys.redhat.com/puddle/build/OpenShiftEnterprise/3.0/latest/RH7-RHOSE-3.0/$basearch/os', 'enabled': 1, 'gpgcheck': 0}]

# Pre-release Errata puddle repo
#openshift_additional_repos=[{'id': 'ose-devel', 'name': 'ose-devel', 'baseurl': 'http://buildvm-devops.usersys.redhat.com/puddle/build/OpenShiftEnterpriseErrata/3.0/latest/RH7-RHOSE-3.0/$basearch/os', 'enabled': 1, 'gpgcheck': 0}]

# Origin copr repo
#openshift_additional_repos=[{'id': 'openshift-origin-copr', 'name': 'OpenShift Origin COPR', 'baseurl': 'https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/epel-7-$basearch/', 'enabled': 1, 'gpgcheck': 1, gpgkey: 'https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/pubkey.gpg'}]

# htpasswd auth
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/openshift/htpasswd'}]

# Allow all auth
#openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]

# master cluster ha variables using pacemaker or RHEL HA
#openshift_master_cluster_password=openshift_cluster
#openshift_master_cluster_vip=192.168.133.25
#openshift_master_cluster_public_vip=192.168.133.25
#openshift_master_cluster_hostname=openshift-ansible.test.example.com
#openshift_master_cluster_public_hostname=openshift-ansible.test.example.com

openshift_master_cluster_password=sanjiang2015
openshift_master_cluster_vip=193.0.10.169
openshift_master_cluster_public_vip=193.0.10.169
openshift_master_cluster_hostname=master.cloud.sanjiang.info
openshift_master_cluster_public_hostname=master.cloud.sanjiang.info


# master cluster ha variables when using a different HA solution
# For installation the value of openshift_master_cluster_hostname must resolve
# to the first master defined in the inventory.
# The HA solution must be manually configured after installation and must ensure
# that openshift-master is running on a single master host.
#openshift_master_cluster_hostname=openshift-ansible.test.example.com
#openshift_master_cluster_public_hostname=openshift-ansible.test.example.com
#openshift_master_cluster_defer_ha=True

# default subdomain to use for exposed routes
osm_default_subdomain=cloud.sanjiang.info

# additional cors origins
#osm_custom_cors_origins=['foo.example.com', 'bar.example.com']

# default project node selector
#osm_default_node_selector='region=primary'

# host group for masters
[masters]
m[1:3].cloud.sanjiang.info

[etcd]
m[1:3].cloud.sanjiang.info

# host group for nodes
[nodes]
m[1:3].cloud.sanjiang.info openshift_scheduleable=False openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
n[1:5].cloud.sanjiang.info openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
```

**Comment by EricSites** [comment] 2015-09-03 23:38
@pstinghua I also had this problem. For some reason the hostname defined here: openshift_master_cluster_public_hostname was not added to the server cert, so when the nodes try to connect they can't verify the cert.

Here is the error message I am getting on the node:
Sep  2 02:11:05 r610-02 openshift-node: E0902 02:11:05.704538   29263 reflector.go:180] pkg/kubelet/kubelet.go:178: Failed to list *api.Service: Get https://admin.example.io:8443/api/v1/services: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, openshift, openshift.default, openshift.default.svc, openshift.default.svc.cluster.local, 10.2.2.1, 127.0.0.1, 172.17.42.1, 192.168.8.1, not admin.example.io

Lots of error messages like that in /var/log/messages file.

I modified the /etc/openshift/node/system:node:node2.example.io.kubeconfig file and changed the server: to https://192.168.2.1:8443
then restarted the sudo systemctl restart openshift-node
And the node was able to connect to the master.

**Comment by pstinghua** [comment] 2015-09-12 05:45
It's ok if set openshift_pkg_version to 1.0.4

**Comment by abutcher** [comment] 2015-11-11 16:48
@pstinghua Closing this issue since it seems you've got it working or the issue is resolved in a recent release. Please re-open if this is not the case. Thanks!

@brenton Please close this issue.

**Closed** 2015-11-11 16:50 UTC
