### ISSUE TITLE
docker_image_availability failure even if osm_etcd_image set

### ISSUE THREAD

**Issue by jsuchenia** [openshift/openshift-ansible#6720] opened 2018-01-14 18:11 UTC
#### Description
To use local mirror of all needed OpenShift components I'm setting `oreg_url`, `osn_ovs_image` and `osm_etcd_image` variables.
But looks like address to ETCD image is hardcoded in docker check, no matter if etcd_image was overwritten or not
https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/openshift_health_checker/openshift_checks/docker_image_availability.py#L172

##### Version
Openshift Ansible: 3.7
Openshift Origin: 3.7

##### Steps To Reproduce
1. Disable access to docker.io
2. Set'up `osm_etcd_image` variable to point to other available URL
3. Run Ansible provisioning

##### Expected Results
Installation should check existence of etcd_image, not hardcoded value

##### Observed Results
Installation failed with hardcoded value

**Comment by sosiouxme** [comment] 2018-01-15 17:38
This appears to be a duplicate of https://github.com/openshift/openshift-ansible/issues/6720 (though that was for 3.6). I'll plan to track it there.

**Closed by sosiouxme** 2018-01-15 17:38 UTC
Labels: affects_3.6, affects_3.7, affects_3.8, area/install-upgrade, kind/bug

**Comment by jsuchenia** [comment] 2018-01-15 18:47
@sosiouxme To be honest #6720 is an Id of this ticket, could you point a reference to proper bug

**Comment by sosiouxme** [comment] 2018-01-25 21:38
Sorry, I meant https://github.com/openshift/openshift-ansible/issues/5330

I opened https://bugzilla.redhat.com/show_bug.cgi?id=1538806
