### ISSUE TITLE
origin37 repo not in release-3.7

### ISSUE THREAD

**Issue by HoogWater** [openshift/openshift-ansible#6375] opened 2017-12-06 18:17 UTC
#### Description

Provide a brief description of your issue here. For example:

> when running a origin install with release-3.7 branch it i need to add the testing branch,
> or an additional repo to get the correct version of origin-docker-excluder and other excluder packages.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
2.4.1.0

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
openshift-ansible-3.7.13-1-2-gdf61aeceb
```

##### Steps To Reproduce
1. git clone the repo
2. run ansible playbook to install origin

##### Expected Results
Describe what you expected to happen.
A full install of origin

```
ansible-playbook -i inventory openshift-ansible/playbooks/byo/config.yml
```

##### Observed Results
Describe what is actually happening.
Installation fails on missing origin-docker-excluder packages
```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
there is no template in the release-3.7 branch for the actual origin37 repository
i would also expect the 37 repo to be available on the centos mirror page

i now need to manually add an additional repository in my inventory pointing to 
https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin37/

i would think that with the official release of origin 37 this would be available at
http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin36/
and that this would be added via a template like the previous versions.
```

**Comment by DanyC97** [comment] 2018-04-19 11:09
@HoogWater any chance you can try with latest 3.7 release ? 

If the problem is no longer present, please close this issue

**Closed** 2020-07-22 13:25 UTC
Labels: lifecycle/rotten
