### ISSUE TITLE
installtion failure 

### ISSUE THREAD

**Issue by pint12** [openshift/openshift-ansible#3228] opened 2017-01-31 08:20 UTC
#### Description

Provide a brief description of your issue here. For example:
tried to follow the installation as introduced in the youtube you published . 
and got the following err 

TASK [openshift_master : set_fact] *********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RepresenterError: cannot represent an object: htpasswd_auth
fatal: [console.techdope.io]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
ansible 2.2.1.0

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by abutcher** [comment] 2017-01-31 15:18
Hey @pint12, we've encountered issues with ansible-2.2.1.0 (see #3111) and you will need to downgrade to ansible-2.2.0.0 until those issues are resolved. Closing as a dupe of #3111, please comment there if you have any issues/concerns.

**Closed by abutcher** 2017-01-31 15:18 UTC
