### ISSUE TITLE
Add Jenkins v3.7 tag to the RHEL7 image streams

### ISSUE THREAD

**Issue by siamaksade** [openshift/openshift-ansible#7104] opened 2018-02-12 12:58 UTC
The `latest` tag for Jenkins image in Red Hat container catalogue does not point to the latest Jenkins version anymore and points indefinitely to the version shipped with OpenShift 3.6. The RHEL 7 image streams json file (`image-streams-rhel7.json`) only imports the Jenkins `latest` tags which means it would deploy older versions of Jenkins on OpenShift 3.7+ by default.

The Jenkins 3.7 tag should be included in `image-streams-rhel7.json` to allow OpenShift 3.7+ users to deploy newer versions of Jenkins without having to figure out how to import tags and images into OpenShift.

```
{  
   "kind":"ImageStream",
   "apiVersion":"v1",
   "metadata":{  
      "name":"jenkins",
      "annotations":{  
         "openshift.io/display-name":"Jenkins"
      }
   },
   "spec":{  
      "tags":[  
          ...
          ,
         {  
            "name":"v3.7",
            "annotations":{  
               "openshift.io/display-name":"Jenkins 2.X",
               "openshift.io/provider-display-name":"Red Hat, Inc.",
               "description":"Provides a Jenkins 2.X server on RHEL 7. For more information about using this container image, including OpenShift considerations, see https://github.com/openshift/jenkins/blob/master/README.md.",
               "iconClass":"icon-jenkins",
               "tags":"jenkins",
               "version":"2.x"
            },
            "from":{  
               "kind":"DockerImage",
               "name":"registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.7"
            }
         }

      ]
   }
}
```

**Comment by siamaksade** [comment] 2018-02-12 12:58
@bparees

**Comment by bparees** [comment] 2018-02-12 14:55
dupe of https://github.com/openshift/openshift-ansible/issues/7027

**Closed by bparees** 2018-02-12 14:55 UTC
