### ISSUE TITLE
ansible related errors when running the aggregated-logging tasks.

### ISSUE THREAD

**Issue by jayunit100** [openshift/openshift-ansible#1838] opened 2016-04-28 19:29 UTC
**these may not be entirely related to aggregated-logging, or even openshift-ansible, ill update this ticket as necessary to reflect the final conclusion** @rflourenc @rlourenc 

Problem:

When I run the openshift ansible task against the openshift_hosted_logging_efk yaml file 
```
[cloud-user@support ansible]$ ANSIBLE_ROLES_PATH=~/openshift-ansible/roles ansible-playbook -i ~/inventory.openshift-enterprise-300nodes openshift_hosted_logging_efk.yaml  -vvv
```
I get a crypric error... 
```
ERROR: fail is not a legal parameter in an Ansible task or handler
```
System Info: Openshift-ansible is at head (April 27)
```
f1fc354da246f9adfe3e25fba79a72fff0cf7b2e 
```

This doesn't actually seem to report a line number.  i assume its associated with the `-fail:` directives.  ?

Notes:

I tried several ansible versions, it always seems to break (`for x in `git tag | grep v1|grep -v rc` ; do git checkout $x && echo $x && ANSIBLE_ROLES_PATH=/usr/share/ansible/openshift-ansible/roles ansible-playbook -i ~/inventory.openshift-enterprise-300nodes openshift_hosted_logging_efk.yaml ; sleep 1 ; done`) on the `-fail` step.

**Comment by jayunit100** [comment] 2016-04-28 19:56
UPDATE
- Running ansible from source, 
- using 2.0
- updating the ansible submodules: `git submodule update --init --recursive` 
seems to get me further, now hitting 
```
TASK [openshift_facts : set_fact] **********************************************
task path: /home/cloud-user/openshift-ansible/roles/openshift_facts/tasks/main.yml:15
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/opt/jay/ansible/lib/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/opt/jay/ansible/lib/ansible/executor/task_executor.py", line 379, in _execute
    self._task.post_validate(templar=templar)
  File "/opt/jay/ansible/lib/ansible/playbook/task.py", line 234, in post_validate
    super(Task, self).post_validate(templar)
  File "/opt/jay/ansible/lib/ansible/playbook/base.py", line 309, in post_validate
    value = templar.template(getattr(self, name))
  File "/opt/jay/ansible/lib/ansible/template/__init__.py", line 359, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/opt/jay/ansible/lib/ansible/template/__init__.py", line 331, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/opt/jay/ansible/lib/ansible/template/__init__.py", line 468, in _do_template
    myenv.filters.update(self._get_filters())
  File "/opt/jay/ansible/lib/ansible/template/__init__.py", line 187, in _get_filters
    plugins = [x for x in self._filter_loader.all()]
  File "/opt/jay/ansible/lib/ansible/plugins/__init__.py", line 349, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/opt/jay/ansible/lib/ansible/plugins/__init__.py", line 313, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/share/ansible_plugins/filter_plugins/openshift_master.py", line 12, in <module>
    from ansible.runner.filter_plugins.core import bool as ansible_bool
ImportError: No module named runner.filter_plugins.core
```

**Comment by detiber** [comment] 2016-04-28 20:29
Closing, since this is a duplicate of https://github.com/openshift/openshift-ansible/issues/686 and https://github.com/openshift/openshift-ansible/issues/1686

Work is ongoing to address the remaining Ansible 2.0 compatibility issues.

**Comment by jayunit100** [comment] 2016-04-28 20:45
@brenton does running the logging stuff require ansible 2.0 ?  or can it run in 1.x?

**Comment by brenton** [comment] 2016-04-28 20:52
Nothing should require Ansible 2.0.  I know there's a PR in progress that should keep things backwards compatible.  @abutcher, mind taking a look?

**Comment by detiber** [comment] 2016-04-28 21:02
@JayKayy this PR should address the error you are hitting: https://github.com/openshift/openshift-ansible/pull/1840

**Comment by jayunit100** [comment] 2016-04-29 01:30
Here we go@rflorenc this is what we need

**Closed** 2016-04-29 05:07 UTC
Labels: kind/bug, priority/P1

**Comment by rflorenc** [comment] 2016-05-02 15:53
@jayunit100, got it.
