### ISSUE TITLE
During upgrade registry is made secure but only serving HTTP

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#2648] opened 2016-10-24 13:52 UTC
This is my rough summarization of a users@lists.openshift.com posting. This may be fixed by now, this is an older version. @gravis can fill in more info
##### Version

openshift-ansible-3.3.22
##### Steps To Reproduce
1. Install 1.2 w/o registry console and secured registry
2. Upgrade to 1.3 using openshift-ansible-3.3.22
##### Current Result

Registry is considered secure but serving HTTP only. Builds, pushes, and pulls fail.
##### Expected Result

Registry is secured and serving HTTPS. Builds, pushes, and pulls work.
##### Additional Information

https://github.com/openshift/origin/issues/11164 maybe related

**Comment by sdodson** [comment] 2016-10-24 13:53
@gravis can you please fill in any additional details

**Comment by gravis** [comment] 2016-10-24 15:40
Thanks a lot @sdodson for taking the time to fill this issue.

Actually, the steps are wrong:

1. Install 1.2 w/o registry console and **IN**secured registry

That's the problem I guess, Ansible thinks the registry IS secured, but it's not.
It was installed / setup by ansible when we created the cluster, and the registry is still not secured today:

```
-bash-4.2# curl -XGET http://172.30.201.95:5000/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

Maybe we missed something in the playbook?

Thanks

**Comment by gravis** [comment] 2016-10-24 15:44
ho "w/o", sorry, was reading too quick

**Comment by abutcher** [comment] 2016-10-24 21:16
I was able to reproduce this but I'm pretty confused as to what is happening. So, I created a 1.2 cluster using the `release-1.2` branch and then I upgraded to 1.3 with the `openshift-ansible-3.3.22-1` tag and my builds were unable to push to the registry with the error `http: server gave HTTP response to HTTPS client`. No changes were made to the registry DC during upgrade aside from changing the image version so we still have an insecure registry.

I then edited `/etc/sysconfig/docker` to add my specific docker-registry service IP and port as an insecure registry alongside the CIDR config.

```
OPTIONS=' --selinux-enabled --insecure-registry=172.30.0.0/16 --insecure-registry=172.30.115.197:5000 --log-driver=json-file --log-opt max-size=50m'
```

After making that change builds/pushes were successful so I tried removing the IP:PORT config and leaving the CIDR config and I was still able to build/push to the registry.

```
OPTIONS=' --selinux-enabled --insecure-registry=172.30.0.0/16 --log-driver=json-file --log-opt max-size=50m'
```

**Comment by gravis** [comment] 2016-10-24 21:20
of course adding `--insecure-registry=172.30.0.0/16` fixed the issue, but after a new ansible run, the `OPTIONS` is restored without this param, and builds / deploys / mostly everything will start to fall apart :(

**Comment by abutcher** [comment] 2016-10-24 21:21
Ah, okay maybe some wires are crossed with that parameter. I will investigate that.

**Comment by gravis** [comment] 2016-10-24 21:21
Thanks :)

**Comment by abutcher** [comment] 2016-10-24 21:34
In the meantime, setting `openshift_docker_hosted_registry_insecure=True` should ensure that `--insecure-registry=172.30.0.0/16` stays in the config on new runs. We default this to false in newer versions since we secure the registry but it needs some more logic.

**Comment by sdodson** [comment] 2016-10-25 13:20
Bug on this https://bugzilla.redhat.com/show_bug.cgi?id=1388016

**Comment by gravis** [comment] 2016-10-27 20:27
We have updated our openshift-ansible repo, with #2670 included, and still the same issue.
`--insecure-registry=172.30.0.0/16` is removed from docker config

**Comment by abutcher** [comment] 2016-10-27 20:32
@gravis Is `hosted_registry_insecure` set to false in `/etc/ansible/facts.d/openshift.fact`?

**Comment by gravis** [comment] 2016-10-27 20:41
`"insecure_registries": [], "additional_registries": [], "hosted_registry_insecure": false`

ansible is still running, and I had to update nodes by hand a second time, docker restarted again without that option :(

**Comment by abutcher** [comment] 2016-10-27 20:48
The currently cached `hosted_registry_insecure` that we got as a result of upgrading is now persisted as false, so it's unfortunately going to stay that way unless `openshift_hosted_registry_insecure=true` is set in the inventory or that fact is removed from `/etc/ansible/facts.d/openshift.fact`.

**Comment by gravis** [comment] 2016-10-27 20:54
Ok, thanks, let me try this.

**Comment by gravis** [comment] 2016-10-27 20:57
Nope, `--insecure-registry=172.30.0.0/16` is still removed, and facts still contains `"insecure_registries": [], "additional_registries": [], "hosted_registry_insecure": false`

:(

**Comment by gravis** [comment] 2016-10-28 00:53
the var is apparently `openshift_docker_hosted_registry_insecure` instead of `openshift_hosted_registry_insecure`, can you confirm please?

**Comment by abutcher** [comment] 2016-10-28 14:00
@gravis Confirmed, that's the right var, sorry!

**Comment by abutcher** [comment] 2016-11-14 20:35
Closing this issue, please update/re-open if encountered again. I think the problem persisted originally since the upgrade flipped the fact for us but should remain set on subsequent runs now that we check the docker config for insecure registries set in the `OPTIONS` line.

**Closed by abutcher** 2016-11-14 20:35 UTC
Labels: backport/3.3, kind/bug, priority/P1
