### ISSUE TITLE
FAILED - RETRYING: Wait for control plane pods to appear

### ISSUE THREAD

**Issue by aland-zhang** [openshift/openshift-ansible#9575] opened 2018-08-14 08:52 UTC
Description
I'm trying a new installation of MASTER branch and v3.10.0 ,it's failing when installing the Master with:

Control plane install failed.
Version
Ansible: ansible 2.6.2
openshift_release=v3.10.0
openshift_image_tag=v3.10.0
openshift_pkg_version=-3.10.0-1.el7.git.0.0c4577e
RPM: package openshift-ansible is not installed
Steps To Reproduce
Follow all pre-requisits
git clone https://github.com/openshift/openshift-ansible
cd openshift-ansible
ansible-playbook playbooks/prerequisites.yml
ansible-playbook playbooks/deploy_cluster.yml

```
TASK [openshift_control_plane : Wait for control plane pods to appear] ************************************************************************************************************************************************************
Tuesday 14 August 2018  16:39:24 +0800 (0:00:00.086)       0:22:42.301 ******** 
FAILED - RETRYING: Wait for control plane pods to appear (60 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (59 retries left).
...............
FAILED - RETRYING: Wait for control plane pods to appear (1 retries left).
failed: [10.10.244.212] (item=__omit_place_holder__5e245b7f796113e2f9ba55e6c4a882ef0471a251) => {"attempts": 60, "changed": false, "item": "__omit_place_holder__5e245b7f796113e2f9ba55e6c4a882ef0471a251", "msg": {"cmd": "/bin/oc get pod master-__omit_place_holder__5e245b7f796113e2f9ba55e6c4a882ef0471a251-10.10.244.212 -o json -n kube-system", "results": [{}], "returncode": 1, "stderr": "The connection to the server 10.10.244.212:8443 was refused - did you specify the right host or port?\n", "stdout": ""}}
```

journalctl -flu docker.service

```
Aug 14 16:46:15 10-10-244-212 dockerd-current[26428]: F0814 08:46:15.849128       1 start_api.go:68] could not load config file "/etc/origin/master/master-config.yaml" due to an error: error reading config: only encoded map or array can be decoded into a struct
Aug 14 16:46:15 10-10-244-212 dockerd-current[26428]: time="2018-08-14T16:46:15.911550511+08:00" level=error msg="containerd: deleting container" error="exit status 1: \"container 30483e504b05f46127fb81b73dab375fb5429096535b0611a07bcdae7505a25c does not exist\\none or more of the container deletions failed\\n\""
Aug 14 16:46:15 10-10-244-212 dockerd-current[26428]: time="2018-08-14T16:46:15.924794132+08:00" level=warning msg="30483e504b05f46127fb81b73dab375fb5429096535b0611a07bcdae7505a25c cleanup: failed to unmount secrets: invalid argument"
Aug 14 16:46:18 10-10-244-212 dockerd-current[26428]: time="2018-08-14T16:46:18.576959765+08:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container 75cfd311e6f33a696b4935b380294e3f6158723a9352357f8aaff3b9da14d31f"
```

**Comment by jhaohai** [comment] 2018-08-15 10:14
We have same issue deploy origin-3.10 with openshift-ansible-3.10.27 rpm installer

**Comment by DanyC97** [comment] 2018-08-15 12:48
@jhaohai @aland-zhang tomorrow morning after 09:00 UTC there should be a new rpm as mentioned [here](https://github.com/openshift/openshift-ansible/issues/8399#issuecomment-413148830), can you please give that a go and let us know ? 

Between `openshift-ansible-3.10.27-1` & `openshift-ansible-3.10.28-1` few fixes got in which i think it touched the parsing error

**Comment by jhaohai** [comment] 2018-08-16 03:36
@DanyC97 Thanks, but I tried a fresh installation and this issue still exist. 
The audit config from example inventory 
`openshift_master_audit_config={"enabled": "true"}` 
will generated as below
```
auditConfig:
  enabled: 'true'
```

**Comment by aland-zhang** [comment] 2018-08-16 05:56
@DanyC97  I installed openshift-ansible-3.10.28-1.git.0.9242c73.noarch.rpm and Still showing the same error :
```
TASK [openshift_control_plane : Report control plane errors] **********************************************************************
fatal: [10.10.244.212]: FAILED! => {"changed": false, "msg": "Control plane pods didn't come up"}
Failure summary:
  1. Hosts:    10.10.244.212
     Play:     Configure masters
     Task:     Report control plane errors
     Message:  Control plane pods didn't come up
```

These dockers have been pulled and completed：
```
$ docker images                                                                                  
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
docker.io/openshift/origin-node            v3.10.0             9f1821bc44c6        35 hours ago        1.27 GB
docker.io/openshift/origin-control-plane   v3.10.0             7454912cb385        35 hours ago        816 MB
docker.io/openshift/origin-pod             v3.10.0             105d0a0070c3        36 hours ago        223 MB
docker.io/openshift/origin-web-console     v3.10.0             7098d8b0a928        13 days ago         337 MB
registry.access.redhat.com/rhel7/etcd      latest              bb2f1d4dd3a7        7 weeks ago         256 MB

```

**Comment by DanyC97** [comment] 2018-08-16 06:04
@aland-zhang i wonder if you are suffering from this issue https://github.com/openshift/openshift-ansible/pull/9620

**Comment by aland-zhang** [comment] 2018-08-16 06:54
I didn't have this issue #9620，I encountered "Control plane pods didn't come up" error and install stopped.

**Comment by jhaohai** [comment] 2018-08-16 07:00
@aland-zhang The detailed logs are in failed pods. Checkout the log with
```
docker ps -a
docker logs -f --tail 10 <container-id>
```

**Comment by aland-zhang** [comment] 2018-08-16 07:09
k8s_api_master-api-10-10-244-212_kube-system_9ca23c5815da8ed1d3dca61d87e1f6ab_33

**Comment by jhaohai** [comment] 2018-08-16 08:06
@aland-zhang [https://bugzilla.redhat.com/show_bug.cgi?id=1589063#c3](url) there is same issue in bugzilla

**Comment by vrutkovs** [comment] 2018-08-16 08:38
Duplicate of #9619

**Closed by vrutkovs** 2018-08-16 08:38 UTC

**Comment by DanyC97** [comment] 2018-08-16 08:45
@vrutkovs cheers, so i was right in saying the PR does fix the issue ;)

**Comment by cello86** [comment] 2018-08-22 06:48
Hi All,
I noticed the same behavior with the openshift-ansible-3.10.33-1.

On master nodes the pod k8s_api_master-api... is exited and the problem is related to a missing connectivity to etcd.

```
[root@ocp-devmaster01 openshift-ansible]# docker logs -f --tail=10 750c9e7631eb
I0822 06:45:20.892219       1 plugins.go:84] Registered admission plugin "PodTolerationRestriction"
I0822 06:45:20.892233       1 plugins.go:84] Registered admission plugin "ResourceQuota"
I0822 06:45:20.892246       1 plugins.go:84] Registered admission plugin "PodSecurityPolicy"
I0822 06:45:20.892258       1 plugins.go:84] Registered admission plugin "Priority"
I0822 06:45:20.892273       1 plugins.go:84] Registered admission plugin "SecurityContextDeny"
I0822 06:45:20.892286       1 plugins.go:84] Registered admission plugin "ServiceAccount"
I0822 06:45:20.892305       1 plugins.go:84] Registered admission plugin "DefaultStorageClass"
I0822 06:45:20.892318       1 plugins.go:84] Registered admission plugin "PersistentVolumeClaimResize"
I0822 06:45:20.892334       1 plugins.go:84] Registered admission plugin "StorageObjectInUseProtection"
F0822 06:45:50.897544       1 start_api.go:68] dial tcp 192.168.98.208:2379: getsockopt: connection refused
```

The etcd container isn't running on the master nodes.

Marcello

**Comment by whitingjr** [comment] 2018-08-28 15:47
Same here. Dumping the log of the `master api` image shows a file is missing. Causing the service to fail on startup.
```
# docker logs -f --tail 10 k8s_api_master-api-server7_kube-system_5946c1f644096161a1242b3de0ee5875_3085
Invalid MasterConfig /etc/origin/master/master-config.yaml
  oauthConfig.identityProvider[0].provider.file: Invalid value: "/etc/origin/openshift-passwd": could not read file: stat /etc/origin/openshift-passwd: no such file or directory
#
```
Inspecting the logs for the `master controller` image shows the same missing file as well.
```
# docker logs -f --tail 10 k8s_controllers_master-controllers-benchserver7_kube-system_8e879171c85e221fb0a023e3f10ca276_3084
Invalid MasterConfig /etc/origin/master/master-config.yaml
  oauthConfig.identityProvider[0].provider.file: Invalid value: "/etc/origin/openshift-passwd": could not read file: stat /etc/origin/openshift-passwd: no such file or directory
#
```
Dropping into the `master api` image to double check the missing file shows the directory the file should be in is missing
```
# docker run -it --entrypoint /bin/bash  registry.access.redhat.com/openshift3/ose-control-plane
Unable to find image 'registry.access.redhat.com/openshift3/ose-control-plane:latest' locally
Trying to pull repository registry.access.redhat.com/openshift3/ose-control-plane ... 
latest: Pulling from registry.access.redhat.com/openshift3/ose-control-plane
Digest: sha256:fb05ab7dad76f91201660824a5e88d4e17989fb2ef34ce0522eafd7604cf41f0
Status: Downloaded newer image for registry.access.redhat.com/openshift3/ose-control-plane:latest
[root@0f1f30e36bfd origin]# ls /etc/origin
ls: cannot access /etc/origin: No such file or directory
[root@0f1f30e36bfd origin]#
```
Shouldn't the image(s) contain this directory ?

**Comment by vrutkovs** [comment] 2018-08-28 15:51
>oauthConfig.identityProvider[0].provider.file: Invalid value: "/etc/origin/openshift-passwd": could not read file: stat /etc/origin/openshift-passwd: no such file or directory

Looks like your `openshift_master_identity_providers` has incorrect path to htpasswd. Is this file present on the host?

**Comment by vrutkovs** [comment] 2018-08-29 06:13
Does it work if its moved to `/etc/origin/master`?

**Comment by whitingjr** [comment] 2018-08-29 09:08
Correction. My last comment was incorrect. The file is not present on the host.

**Comment by vrutkovs** [comment] 2018-08-29 14:14
Folks, 'Wait for control plane pods to appear' failing means API server failed to start. There might be a billion reasons for that - unreachable pod image pullspec, wrong API server configuration, something wring with docker etc.

Lets not post 'I have this issue too' comments, because the same symptom doesn't mean the same issue is causing it - or that ansible playbooks are incorrect.

**Comment by whitingjr** [comment] 2018-08-30 07:44
@vrutkovs Your absolutely right. Sorry.

**Comment by ramanjk** [comment] 2018-10-15 11:39
facing the same issue...i am suspecting that its a DNS issue..i checked before and after the config.yml script executiion that DNS name is changing...

[root@master ~]# cat /etc/resolv.conf
# nameserver updated by /etc/NetworkManager/dispatcher.d/99-origin-dns.sh
# Generated by NetworkManager
search cluster.local example.com
nameserver 10.0.0.11
[root@master ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0|grep -i DNS
DNS1=10.0.0.1


Openshift error:
TASK [openshift_control_plane : Report control plane errors] **************************************************************************************
fatal: [master.example.com]: FAILED! => {"changed": false, "msg": "Control plane pods didn't come up"}

fatal: [master.example.com]: FAILED! => {"changed": true, "cmd": ["oc", "get", "events", "--config=/etc/origin/master/admin.kubeconfig", "-n", "kube-system"], "delta": "0:00:00.208492", "end": "2018-10-15 16:36:02.875601", "msg": "non-zero return code", "rc": 1, "start": "2018-10-15 16:36:02.667109", "stderr": "The connection to the server master.example.com:8443 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server master.example.com:8443 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}
                         
                             Please suggest any resolution.

**Comment by vinodmsharma** [comment] 2019-01-08 06:48
1. Make sure the hostname command on your host give FQDN, if not set it with `hostnamectl set-hostname <FQDN hostname>`

Add below properties in `/etc/sysconfig/network-scripts/ifcfg-<interface_name>`
```
NM_CONTROLLED=yes
PEERDNS=yes
```

Also to fix upstream DNS quickly you can follow below suppose your DNS addresses are 10.99.1.2 and 10.99.1.3

```
# nmcli con mod ens192 ipv4.dns 10.99.1.2,10.99.1.3
# systemctl restart NetworkManager
# systemctl restart dnsmasq
# cat /etc/dnsmasq.d/origin-upstream-dns.conf
# cat /etc/resolv.conf
```
