### ISSUE TITLE
New deployment on 3.10 unable to start with control plane errors

### ISSUE THREAD

**Issue by putz612** [openshift/openshift-ansible#10384] opened 2018-10-11 15:26 UTC
#### Description

New deployment of 3.10 onto CentOS 7.5 and I am unable to get past TASK [openshift_control_plane : Wait for control plane pods to appear]

##### Version

```
ansible 2.7.0
  config file = /home/jsievert/work/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/jsievert/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

openshift-ansible-3.10.53-1-8-g5bfd3d76f


```

##### Steps To Reproduce
1. Deploy fresh new systems
2. Create inventory file 
3. Run ansible-playbook  playbooks/deploy_cluster.yml

##### Expected Results
Fresh awesomeness of OpenShift!  

```
# ansible-playbook  playbooks/deploy_cluster.yml
.
.
.
TASK [openshift_control_plane : Wait for control plane pods to appear] *********************************************************************************************************
Thursday 11 October 2018  10:03:52 -0500 (0:00:00.051)       0:08:50.596 ****** 
FAILED - RETRYING: Wait for control plane pods to appear (60 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (59 retries left).
.
.
TASK [openshift_control_plane : Report control plane errors] *******************************************************************************************************************
Wednesday 10 October 2018  13:59:08 -0500 (0:00:00.116)       0:26:48.271 ***** 
fatal: [osom0.interplx.local]: FAILED! => {"changed": false, "msg": "Control plane pods didn't come up"}

```

##### Observed Results

What I see in the master is containers failing, specifically k8s_controllers_master-controllers and k8s_api_master-api.  Grabbing the logs from the container while I can I see this
```
Invalid MasterConfig /etc/origin/master/master-config.yaml
  etcdClientInfo.ca: Invalid value: "/etc/origin/master/master.etcd-ca.crt": could not read file: stat /etc/origin/master/master.etcd-ca.crt: no such file or directory
```
Looking on the master I do not see that file

```
# ls /etc/origin/master/master.etcd-ca.crt
ls: cannot access /etc/origin/master/master.etcd-ca.crt: No such file or directory
```
However I do see others that are close, just not the ca.crt file

```
# ls /etc/origin/master/master.etcd*
/etc/origin/master/master.etcd-client.crt  
/etc/origin/master/master.etcd-client.key
```

##### Additional Information

```
#####redhat-release
CentOS Linux release 7.5.1804 (Core) 

#####Inventory file
[OSEv3:children]
masters
nodes
etcd
[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=origin
openshift_install_examples=false
openshift_hosted_templates=false
openshift_master_default_subdomain=oso.ix.local

[masters]
osom0.ix.local

[etcd]
osom0.ix.local

[nodes]
osom0.ix.local openshift_node_group_name='node-config-master'
oson0.ix.local openshift_node_group_name='node-config-compute'
oson1.ix.local openshift_node_group_name='node-config-compute'
osoi0.ix.local openshift_node_group_name='node-config-infra'
```

**Comment by vrutkovs** [comment] 2018-10-11 15:38
Duplicate of #10368

**Closed by vrutkovs** 2018-10-11 15:38 UTC
