### ISSUE TITLE
Origin Version conflict

### ISSUE THREAD

**Issue by dungdm93** [openshift/openshift-ansible#7577] opened 2018-03-20 04:27 UTC
### Description
I install OpenShift 3.7 but I got following error:
```
TASK [openshift_master_facts : Set Default scheduler predicates and priorities] ***********************************************************************************************************************************
Tuesday 20 March 2018  10:56:52 +0700 (0:00:02.492)       0:11:51.034 ********* 
fatal: [35.193.226.101]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unknown short_version 3.10"}
ok: [35.193.72.204]
ok: [35.188.14.31]
```
After a while checking on my servers,  I found that origin 3.7 was installed but when I run `origin version`, version 3.10 is shown.
```
[cloud-user@tinhte-master-wff7 ~]$ yum info origin
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.sesp.northwestern.edu
 * epel: mirror.steadfast.net
 * extras: mirror.genesisadaptive.com
 * updates: mirrors.gigenet.com
Installed Packages
Name        : origin
Arch        : x86_64
Version     : 3.7.1
Release     : 1.el7.git.0.0a2d6a1
Size        : 597 M
Repo        : installed
From repo   : centos-openshift-origin37
Summary     : Open Source Container Management by Red Hat
URL         : https://github.com/openshift/origin
License     : ASL 2.0
Description : OpenShift is a distribution of Kubernetes optimized for enterprise application
            : development and deployment. OpenShift adds developer and operational centric
            : tools on top of Kubernetes to enable rapid application development, easy
            : deployment and scaling, and long-term lifecycle maintenance for small and large
            : teams and applications. It provides a secure and multi-tenant configuration for
            : Kubernetes allowing you to safely host many different applications and workloads
            : on a unified cluster.

[cloud-user@tinhte-master-wff7 ~]$ origin version
origin v3.10.0-alpha.0+0a2d6a1-65
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16
[cloud-user@tinhte-master-wff7 ~]$ yum repolist
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.sesp.northwestern.edu
 * epel: mirror.steadfast.net
 * extras: mirror.genesisadaptive.com
 * updates: mirrors.gigenet.com
repo id                                                                                 repo name                                                                                                     status
base/7/x86_64                                                                           CentOS-7 - Base                                                                                                9.591
centos-openshift-origin37                                                               CentOS OpenShift Origin                                                                                           67
epel/x86_64                                                                             Extra Packages for Enterprise Linux 7 - x86_64                                                                12.425
extras/7/x86_64                                                                         CentOS-7 - Extras                                                                                                436
google-cloud-compute                                                                    Google Cloud Compute                                                                                               9
google-cloud-sdk                                                                        Google Cloud SDK                                                                                                 425
updates/7/x86_64                                                                        CentOS-7 - Updates                                                                                             2.407
repolist: 25.360
```

### Version
* `ansible --version`
```
ansible 2.4.3.0
  config file = /me/Workspaces/OpenShift/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/dungdm93/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

* `git describe`
```
openshift-ansible-3.7.39-1-1-g9d6f34f
```

**Comment by DanyC97** [comment] 2018-03-29 09:13
@dungdm93 can you please close this issue as is a duplicate of #7569  ?

Also for future use, please don't open duplicate issues, it doesn't help . thank you for your understanding

**Closed** 2018-03-30 08:06 UTC
