### ISSUE TITLE
Missing v3.7/glusterblock-template.yml

### ISSUE THREAD

**Issue by mcanevet** [openshift/openshift-ansible#6247] opened 2017-11-23 12:09 UTC
#### Description

When enabling `glusterfs` on `release-3.7` branch, I get this error message since 7f99212:
```
(item=glusterblock-template.yml) => {"failed": true, "item": "glusterblock-template.yml", "msg": "Unable to find 'v3.7/glusterblock-template.yml' in expected paths."}
```

**Comment by davivcgarcia** [comment] 2017-11-26 12:24
It seems duplicate of #6218.

**Comment by elajoie** [comment] 2017-12-10 22:26
Same issue:
failed: [master1.lajoie.org] (item=glusterblock-template.yml) => {
    "changed": false, 
    "failed": true, 
    "item": "glusterblock-template.yml", 
    "msg": "Could not find or access 'v3.7/glusterblock-template.yml'\nSearched in:\n\t/usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/files/v3.7/glusterblock-template.yml\n\t/usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/v3.7/glusterblock-template.yml\n\t/usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/tasks/files/v3.7/glusterblock-template.yml\n\t/usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/tasks/v3.7/glusterblock-template.yml\n\t/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-glusterfs/../../common/openshift-glusterfs/files/v3.7/glusterblock-template.yml\n\t/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-glusterfs/../../common/openshift-glusterfs/v3.7/glusterblock-template.yml"
}

The glusterblock-template.yml file is def missing...

**Comment by jarrpa** [comment] 2017-12-11 14:24
Should be resolved by: https://github.com/openshift/openshift-ansible/pull/6273

Could someone verify?

**Comment by jarrpa** [comment] 2017-12-11 14:50
This should have been fixed as of https://github.com/openshift/openshift-ansible/commit/e48474a8a4c584fd5655ba3eb1bde3208300a545#diff-68bfeac0f198eba097e4881930f48c8c

**Comment by DanyC97** [comment] 2018-02-11 11:20
can this be closed please since it was fixed in what @jarrpa mentioned ?

**Closed** 2018-02-11 16:53 UTC
