### ISSUE TITLE
SELinux is disabled

### ISSUE THREAD

**Issue by Aeolun** [openshift/openshift-ansible#9767] opened 2018-08-26 11:48 UTC
#### Description

On (presumably) any install, the prerequisites script does not take into account whether SELinux is enabled, causing a failure during `deploy_cluster.yml`.

##### Version

```
ansible 2.6.3
  config file = /var/www/openshift-ansible/ansible.cfg
  configured module search path = ['/home/bart/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]

openshift-ansible-3.10.35-1-9-g2e49741
```

##### Steps To Reproduce
1. Boot CentOS 7.5 base image
2. Run `prerequisites.yml` playbook
3. Run `deploy_cluster.yml` playbook

##### Expected Results
I expected the playbook to warn me about any invalid settings in the prerequisites check, so that deploy_cluster goes off without a hitch.

##### Observed Results

```
TASK [openshift_node : Setting sebool container_manage_cgroup] *****************************************************
Sunday 26 August 2018  20:39:39 +0900 (0:00:01.984)       0:05:38.773 *********
fatal: [console.cluster.serial-experiments.com]: FAILED! => {"changed": false, "msg": "SELinux is disabled on this host."}
```

**Comment by vrutkovs** [comment] 2018-08-27 05:00
Duplicate of #9150

**Closed by vrutkovs** 2018-08-27 05:00 UTC

**Comment by mottati** [comment] 2018-08-29 17:41
This may in fact be a duplicate of #9150 however _that issue was closed without remediating the underlying issue_. I cloned https://github.com/openshift/openshift-ansible on Aug 28 (after this jira was closed) and got the same error as reported both here and in #9150. 

I would think that adding this check to the prerequisites playbook would be the solution to this issue. The fact that this is a prerequisite is quite clearly called out here: https://docs.openshift.com/container-platform/3.9/install_config/install/prerequisites.html#hardware

Why is this requirement not encoded in the prerequisites playbook?

**Comment by zoobab** [comment] 2018-08-31 08:36
+1 to include it in the requirements.

Just got the same problem with:

```
TASK [openshift_node : Setting sebool container_manage_cgroup] **********************************************************************************************
Friday 31 August 2018  08:31:28 +0000 (0:00:00.732)       0:00:34.685 *********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "SELinux boolean container_manage_cgroup does not exist."}
```

**Comment by morsik** [comment] 2018-09-12 09:19
This requirement exists, but only for `openshift-enterprise` deployment type - for me the bug is there.

See `/opt/openshift-ansible/playbooks/byo/openshift-cluster/roles/openshift_node/tasks/main.yml` at the beginning:
```yaml
- fail:
    msg: "SELinux is disabled, This deployment type requires that SELinux is enabled."
  when:
    - (not ansible_selinux or ansible_selinux.status != 'enabled')
    - openshift_deployment_type == 'openshift-enterprise'
    - not openshift_use_crio | bool
```
