### ISSUE TITLE
AnsibleUndefinedVariable: 'dict object' has no attribute 'dns_ip'

### ISSUE THREAD

**Issue by debianmaster** [openshift/openshift-ansible#5146] opened 2017-08-18 23:58 UTC
#### Description
Openshift origin install failed with ```AnsibleUndefinedVariable: 'dict object' has no attribute 'dns_ip'```

##### Version
```
[root@master1 openshift-ansible]# ansible --version
ansible 2.3.1.0
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

```
[root@master1 openshift-ansible]# git describe
openshift-ansible-3.6.173.0.7-1
```

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

##### Steps To Reproduce
```ansible-playbook -i ../.config/openshift/hosts ./playbooks/byo/config.yml```

##### Expected Results
Install should succeed

```

```

##### Observed Results
Describe what is actually happening.

```
TASK [openshift_node_dnsmasq : Install dnsmasq configuration] *******************************************************************************
fatal: [master1]: FAILED! => {
    "changed": false,
    "failed": true
}

MSG:

AnsibleUndefinedVariable: 'dict object' has no attribute 'dns_ip'

fatal: [infra1]: FAILED! => {
    "changed": false,
    "failed": true

▽
}

MSG:

AnsibleUndefinedVariable: 'dict object' has no attribute 'dns_ip'


PLAY RECAP **********************************************************************************************************************************
infra1                     : ok=186  changed=10   unreachable=0    failed=1
localhost                  : ok=13   changed=0    unreachable=0    failed=0
master1                    : ok=514  changed=34   unreachable=0    failed=1


Failure summary:

  1. Host:     master1
     Play:     Configure nodes
     Task:     openshift_node_dnsmasq : Install dnsmasq configuration
     Message:  AnsibleUndefinedVariable: 'dict object' has no attribute 'dns_ip'

  2. Host:     infra1
     Play:     Configure nodes
     Task:     openshift_node_dnsmasq : Install dnsmasq configuration
     Message:  AnsibleUndefinedVariable: 'dict object' has no attribute 'dns_ip'
```

### Using calico plugin

**Comment by jsuchenia** [comment] 2017-08-19 07:35
I had exactly the same. Looks like it's related to commit f391268ca0f07eddf98836abaeb03d6579365028

**Comment by liornabat** [comment] 2017-08-20 10:24
same here :(

**Comment by tiran** [comment] 2017-08-22 11:32
@sdodson ``ci/openshift-jenkins/extended_conformance_install_update`` is still broken on OpenShift master, see https://github.com/openshift/origin/pull/15896#issuecomment-323996186

**Comment by simo5** [comment] 2017-08-22 12:20
@sdodson this is breaking Origin's CI looks like a P0 to me.

**Comment by sdodson** [comment] 2017-08-22 13:19
This is already fixed. CI jobs are just picking a version of the installer that doesn't have this fix. Working with the CI/CD team to address that. I'll leave this open until we can verify that.

**Comment by sdodson** [comment] 2017-08-22 13:45
https://github.com/openshift/aos-cd-jobs/pull/578 should've fixed CI jobs

**Comment by sdodson** [comment] 2017-08-22 17:10
confirmed, closing

**Closed by sdodson** 2017-08-22 17:10 UTC
