### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by elasti-ronenc** [openshift/openshift-ansible#3160] opened 2017-01-24 14:20 UTC
SSUE TYPE

Bug Report
Feature Idea
Documentation Report
COMPONENT NAME

ANSIBLE VERSION
ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
CONFIGURATION

Config
one master and two nodes

Environemt
centos 7 

**STEPS TO REPRODUCE**

1. install Prerequisites
2. run  atomic-openshift-installer -v install
3. Provide the details

**EXPECTED RESULTS**

Openshift deployment 

**ACTUAL RESULTS**

after running 
atomic-openshift-installer -v install and answering all the questions
i am getting this error :

Gathering information from hosts...
 [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin (</usr/lib/python2.7/site-packages/ooinstall/ansible_plugins/facts_callback.CallbackModule object at 0x229bf90>): cannot represent an object: common
There was a problem fetching the required information. Please see /tmp/ansible.log for details.

**Comment by vanloswang** [comment] 2017-01-24 14:52
openshift-ansible-3.4.56-1 give me the same warning.

**Comment by elasti-ronenc** [comment] 2017-01-24 14:53
Did you manage to deploy ?

**Comment by vanloswang** [comment] 2017-01-24 14:56
@elasti-ronenc the same step as you did. not unattended installation.

**Comment by elasti-ronenc** [comment] 2017-01-24 14:57
Is there is a Friendly way to deploy it ?

**Comment by vanloswang** [comment] 2017-01-25 06:24
@elasti-ronenc it seems like that is caused by ansible, https://github.com/ansible/ansible/issues/16545

**Comment by abutcher** [comment] 2017-01-25 15:46
Hey, this is an issue with ansible 2.2.1.0. Closing as a dupe of https://github.com/openshift/openshift-ansible/issues/3111

**Closed by abutcher** 2017-01-25 15:46 UTC

**Comment by isansahoo** [comment] 2018-06-15 00:20
Getting same issue as above:
```
[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin (<ansible.plugins.callback.facts_callback.CallbackModule object at 0x7fe196a0d950>): 'module' object has no attribute 'dump'
There was a problem fetching the required information. Please see /tmp/ansible.log for details.
```
Some details:
- Installing openshift 3.7
- Ansible version:

```
ansible --version
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

Could you please let know how to solve this issue?
