### ISSUE TITLE
Configuration for upgrade from BYO Origin 1.2.1 to 1.3.0

### ISSUE THREAD

**Issue by LarsMilland** [openshift/openshift-ansible#2481] opened 2016-09-21 12:38 UTC
Hi

I am trying to upgrade an OpenShift Origin cluster/multimaster installation of version 1.2.1 to version 1.3.0 on a RHEL based set of servers using the origin-ansible scripts. But I can't find any RHEL compatible RPM packages in a RPM repository. Are there at all any builds of version 1.3.0 for RHEL around somewhere in a RPM repository? If not will there be one - and how is that created, and where will it be?

I have been pointed to use the RPM repository referenced here: 

https://cbs.centos.org/koji/buildinfo?buildID=12421

But I struggle to figure out how the exact configuration in an origin-ansible hosts file would look like, with the 'openshift_additional_repos' config entry and what would the 'openshift_pkg_version' config entry need to be to select the 1.3.0 version of OpenShift Origin?

Also I should explain that I have run this command:

ansible-playbook playbooks/byo/openshift-cluster/upgrades/v3_2/upgrade.yml

as I understand that is the one that would be able to upgrade an OpenShift Origin 1.2.1 version to a higher version. If that is totally wrong please also correct me here. For instance if I instead is to use another command.

I have also tried:

ansible-playbook playbooks/byo/openshift-cluster/upgrades/v3_3/upgrade.yml

but that claims that I should use that for another version:

Detected OpenShift version 1.2.1 does not match requested openshift_release 1.3. You may need to adjust your yum repositories, inventory, or run the appropriate OpenShift upgrade playbook.

Best regards
Lars Milland

**Comment by sdodson** [comment] 2016-09-21 15:33
The 1.3 RPMs haven't been promoted to the released repos yet. They should be later today, until then you can set 
`openshift_additional_repos=[{'id': 'origin-testing', 'name': 'origin-tesing', 'baseurl': 'http://cbs.centos.org/repos/paas7-openshift-origin-testing/x86_64/os/', 'enabled': 1, 'gpgcheck': 0}]`
Then run `ansible-playbook playbooks/byo/openshift-cluster/upgrades/v3_3/upgrade.yml`

**Comment by sdodson** [comment] 2016-09-21 15:34
While this issue is related to upgrades it's really just a dupe of #2482 so i'm going to close it. The root cause in both is the fact that the Origin 1.3 rpms haven't been promoted to the released repos yet.

**Closed by sdodson** 2016-09-21 15:34 UTC
