### ISSUE TITLE
Openshift Service Catalog - 500 Internal Server error

### ISSUE THREAD

**Issue by riponbanik** [openshift/openshift-ansible#8430] opened 2018-05-18 09:47 UTC
#### Description

Provide a brief description of your issue here. For example:

It is a single master and 2 nodes deployment using ref in using rpm package instead of docker image

https://docs.openshift.org/latest/install_config/install/advanced_install.html#single-master

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

2.4.0

If you're operating from a **git clone**:

* The output of `git describe`

openshift-ansible-3.9.19-1-26-gd328e7dda

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
Openshift service catalog health check fails while running ansible-playbook -i inventory ../openshift-ansible/playbooks/openshift-service-catalog/config.yml -vv

```
TASK [openshift_service_catalog : wait for api server to be ready] *******************************************************************************************
task path: /mnt/e/VMWare/repo/openshift-ansible/roles/openshift_service_catalog/tasks/start_api_server.yml:11
fatal: [controller]: FAILED! => {"attempts": 1, "changed": false, "connection": "close", "content": "[+]ping ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/start-service-catalog-apiserver-informers ok\n[-]etcd failed: reason withheld\nhealthz check failed\n", "content_length": "180", "content_type": "text/plain; charset=utf-8", "date": "Fri, 18 May 2018 07:21:36 GMT", "msg": "Status code was 500 and not [200]: HTTP Error 500: Internal Server Error", "redirected": false, "status": 500, "url": "https://apiserver.kube-service-catalog.svc/healthz", "x_content_type_options": "nosniff"}

##### Expected Results
Describe what you expected to happen.

Service catalog health checks required to be succeeded before running other stes

```

##### Observed Results
Describe what is actually happening.

```
Running the following on Controller

curl -k https://apiserver.kube-service-catalog.svc/
Too many requests, please try again later.

```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
CentOS Linux release 7.4.1708 (Core)

**Inventory**

controller ansible_ssh_host=oc-master.vm.local 
node1      ansible_ssh_host=oc-node1.vm.local  
node2      ansible_ssh_host=oc-node2.vm.local  

[all:vars]
ansible_connection=ssh
ansible_ssh_user=root
ansible_ssh_pass=Passw0rd

[nodes]
controller openshift_schedulable=true openshift_node_labels="{'region': 'infra','zone': 'default'}"  
node[1:2] openshift_schedulable=true openshift_node_labels="{'region': 'primary', 'zone': 'default'}"


[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_become must be set to true
ansible_become=true

# if your target hosts are Fedora uncomment this
#ansible_python_interpreter=/usr/bin/python3
openshift_deployment_type=origin


# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
# openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': #'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

containerized=true
openshift_release=3.9
# openshift_image_tag=latest 
# openshift_pkg_version=v3.9.0
# openshift_version=3.9


#osm_cluster_network_cidr=10.128.0.0/14
#openshift_portal_net=172.30.0.0/16
#osm_host_subnet_length=9

# localhost likely doesn't meet the minimum requirements
openshift_disable_check=disk_availability,docker_image_availability,memory_availability

# Web console to run on master
openshift_web_console_install=false
# openshift_web_console_nodeselector={'region':'infra'}

# Service Catalog
# ansible_service_broker_install=false

# Access service externally
openshift_master_default_subdomain=192.168.23.30.xip.io

[masters]
controller

[etcd]
controller

`````

**Comment by vrutkovs** [comment] 2018-05-18 09:51
Duplicate of #8195

**Closed by vrutkovs** 2018-05-18 09:51 UTC
