### ISSUE TITLE
Installing cluster fails with "Control plane install failed."

### ISSUE THREAD

**Issue by fmq** [openshift/openshift-ansible#8453] opened 2018-05-19 15:53 UTC
#### Description

I'm trying a new installation of MASTER branch and it's failing when installing the Master with:

```
Control plane install failed.
```

##### Version
```
Ansible: ansible 2.5.2
Openshift Version: openshift-ansible-3.10.0-0.47.0-65-g4796c1d
RPM: package openshift-ansible is not installed
```

##### Steps To Reproduce

1. Follow all pre-requisits
2. git clone https://github.com/openshift/openshift-ansible
3. cd openshift-ansible
4. ansible-playbook playbooks/prerequisites.yml
5. ansible-playbook playbooks/deploy_cluster.yml

##### Expected Results

```
Openshift origin 3.10 installed successfully
```

##### Observed Results

```
TASK [openshift_control_plane : fail] *********************************************************************************************************
Friday 18 May 2018  20:12:34 -0300 (0:00:00.046)       0:11:30.859 ************ 
skipping: [origin-m.hospitalaleman.com]

TASK [openshift_control_plane : Verify that the control plane is running] *********************************************************************************************************
Friday 18 May 2018  20:12:34 -0300 (0:00:00.059)       0:11:30.919 ************ 
FAILED - RETRYING: Verify that the control plane is running (60 retries left).
FAILED - RETRYING: Verify that the control plane is running (59 retries left).
FAILED - RETRYING: Verify that the control plane is running (58 retries left).
FAILED - RETRYING: Verify that the control plane is running (57 retries left).
FAILED - RETRYING: Verify that the control plane is running (56 retries left).
FAILED - RETRYING: Verify that the control plane is running (55 retries left).
......
.....
FAILED - RETRYING: Verify that the control plane is running (2 retries left).
FAILED - RETRYING: Verify that the control plane is running (1 retries left).
fatal: [origin-m.hospitalaleman.com]: FAILED! => {"attempts": 60, "changed": false, "cmd": ["curl", "-k", "https://origin-m.hospitalaleman.com:8443/healthz/ready"], "delta": "0:00:00.018986", "end": "2018-05-18 20:17:49.046176", "msg": "non-zero return code", "rc": 7, "start": "2018-05-18 20:17:49.027190", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to origin-m.hospitalaleman.com:8443; Connection refused", "stderr_lines": ["  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to origin-m.hospitalaleman.com:8443; Connection refused"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [openshift_control_plane : Check status in the kube-system namespace] *********************************************************************************************************Friday 18 May 2018  20:17:49 -0300 (0:05:14.345)       0:16:45.265 ************ 
fatal: [origin-m.hospitalaleman.com]: FAILED! => {"changed": true, "cmd": ["oc", "status", "--config=/etc/origin/master/admin.kubeconfig", "-n", "kube-system"], "delta": "0:00:00.150817", "end": "2018-05-18 20:17:49.472223", "msg": "non-zero return code", "rc": 1, "start": "2018-05-18 20:17:49.321406", "stderr": "The connection to the server origin-m.hospitalaleman.com:8443 was refused - did you specify the right host or port?
....
...
TASK [openshift_control_plane : Report control plane errors] ********************************************************************************************************************************************************************************************************
Friday 18 May 2018  20:17:51 -0300 (0:00:00.130)       0:16:47.737 ************ 
fatal: [origin-m.hospitalaleman.com]: FAILED! => {"changed": false, "msg": "Control plane install failed."}

NO MORE HOSTS LEFT *********************************************************************************************************

PLAY RECAP *********************************************************************************************************localhost                  : ok=14   changed=0    unreachable=0    failed=0   
origin-1.hospitalaleman.com : ok=99   changed=33   unreachable=0    failed=0   
origin-m.hospitalaleman.com : ok=295  changed=130  unreachable=0    failed=1   


INSTALLER STATUS *********************************************************************************************************Initialization    : Complete (0:00:13)
Health Check      : Complete (0:00:25)
Node Preparation  : Complete (0:08:54)
etcd Install      : Complete (0:00:31)
Master Install    : In Progress (0:06:45)
	This phase can be restarted by running: playbooks/openshift-master/config.yml
Friday 18 May 2018  20:17:51 -0300 (0:00:00.077)       0:16:47.815 ************ 
```

##### Additional Information

```
OS: CentOS Linux release 7.5.1804 (Core) 
```

**Comment by vponomaryov** [comment] 2018-05-24 08:50
I suspect you faced this -> https://github.com/openshift/openshift-ansible/issues/8133
And it has been fixed in "openshift-ansible-3.10.0-0.51.0".
So, just try this latest version.

**Comment by alexxa** [comment] 2018-06-12 09:31
@vponomaryov, I have just tried "openshift-ansible-3.10.0-0.51.0" a couple of times and it also fails with `Control plane install failed`. Any other ideas, please?

**Comment by lukas-bednar** [comment] 2018-06-12 15:46
@vponomaryov I am running with `openshift-ansible-3.10.0-0.66.0` and I am getting this issue as well.
Here are logs from docker
```
2b998d305800e3eb08b1c38abbffe2374d16c9573cc37b020a/stop?t=10 returned error: Container d207ade86bac4b2b998d305800e3eb08b1c38abbffe2374d16c9573cc37b020a is already stopped"
2b998d305800e3eb08b1c38abbffe2374d16c9573cc37b020a/stop returned error: Container d207ade86bac4b2b998d305800e3eb08b1c38abbffe2374d16c9573cc37b020a is already stopped"
ror: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup configuration for process caused \\\"No such device or address\\\"\"\n" id=760b5cc022bbc
rror: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup configuration for process caused \\\"No such device or address\\\"\"\n"
520fb16afeb8660d6 cleanup: failed to unmount secrets: invalid argument"
791cb8cffc57bdd7e8b03804f352c17ec520fb16afeb8660d6/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup c
791cb8cffc57bdd7e8b03804f352c17ec520fb16afeb8660d6/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup c
s 1: \"container 760b5cc022bbcb791cb8cffc57bdd7e8b03804f352c17ec520fb16afeb8660d6 does not exist\\none or more of the container deletions failed\\n\""
rror: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup configuration for process caused \\\"No such device or address\\\"\"\n" id=fa75149eff14
rror: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup configuration for process caused \\\"No such device or address\\\"\"\n"
6fbdf68389aea994b cleanup: failed to unmount secrets: invalid argument"
2fb7b685d4653e1a7ef61d902a6d42b756fbdf68389aea994b/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup c
2fb7b685d4653e1a7ef61d902a6d42b756fbdf68389aea994b/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup c
s 1: \"container fa75149eff14892fb7b685d4653e1a7ef61d902a6d42b756fbdf68389aea994b does not exist\\none or more of the container deletions failed\\n\""
rror: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup configuration for process caused \\\"No such device or address\\\"\"\n" id=601cc041c2f3
rror: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup configuration for process caused \\\"No such device or address\\\"\"\n"
2645d9f7f5b6c9547 cleanup: failed to unmount secrets: invalid argument"
40caf7ae0031ad0556037dd4e7a55f8d02645d9f7f5b6c9547/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup c
40caf7ae0031ad0556037dd4e7a55f8d02645d9f7f5b6c9547/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup c
s 1: \"container 601cc041c2f3db40caf7ae0031ad0556037dd4e7a55f8d02645d9f7f5b6c9547 does not exist\\none or more of the container deletions failed\\n\""
```

**Comment by alexxa** [comment] 2018-06-12 15:47
cc @vrutkovs

**Comment by vrutkovs** [comment] 2018-06-12 16:46
This looks like docker issue to me, see https://bugzilla.redhat.com/show_bug.cgi?id=1584909

What's your current docker version? Does downgrading it helps?

**Comment by lukas-bednar** [comment] 2018-06-13 08:29
@vrutkovs we are running higher version of docker `docker-1.13.1-66.gitdded712.el7.x86_64`.

**Comment by uocxp** [comment] 2018-08-28 15:27
i have also a similar problem. i am getting
>failed: [os-master] (item=etcd) => {"attempts": 60, "changed": false, "item": "etcd", "msg": {"cmd": "/usr/bin/oc get pod master-etcd-os-master -o json -n kube-system", "results": [{}], "returncode": 1, "stderr": "The connection to the server os-master:8443 was refused - did you specify the right host or port?\n", "stdout": ""}}

i am getting in journalctl allover 
>dial tcp 192.168.1.10:8443: getsockopt: connection refused

etcd and the master sevices are not even installed

i have one master and 3 nodes
```
os-master openshift_schedulable=True  openshift_public_hostname=os-master.tld  openshift_node_group_name='node-config-master-infra'
os-node01 openshift_schedulable=True openshift_public_hostname=os-node01.tld openshift_node_group_name='node-config-compute'
os-node02 openshift_schedulable=True openshift_public_hostname=os-node02.tld openshift_node_group_name='node-config-compute'
os-node03 openshift_schedulable=True openshift_public_hostname=os-node03.tld openshift_node_group_name='node-config-compute'
```

**Comment by DanyC97** [comment] 2018-08-29 08:17
@lukas-bednar if you look [here](http://mirror.centos.org/centos/7/extras/x86_64/Packages/docker-1.13.1-74.git6e3bb8e.el7.centos.x86_64.rpm) you can see a newer docker version and that will be pulled down assuming you are deploying on CentOS 7.4 distro. 

On RHEL check out this doc https://access.redhat.com/articles/2317361 although it might be better to confirm by querying yum rhel repo (i don't have access to so i can confirm)

Also for you and @uocxp / @whitingjr  would suggest to try and get the latest openshift-ansible tag release/ rpm `openshift-ansible-3.10.38-1.git.0.8cfad6d.el7` and give it a run.

If you have issue again, please let us know the OS version `cat /etc/redhat-release` too.

**Comment by lukas-bednar** [comment] 2018-08-29 10:49
@DanyC97 Thank you for info! But with time going forward, we are already on 3.10 , and not seeing this issue anymore.

**Comment by uocxp** [comment] 2018-08-29 11:41
@DanyC97  i am deploying openshift-origin on `CentOS Linux release 7.5.1804` from branch `release-3.10`

**Comment by whitingjr** [comment] 2018-08-29 13:53
@uocxp try running the install ansible script with -vvv and capture the output. You'll then have a chance of finding the root cause of why these services failed to install/start. Good luck.

**Comment by bbomgardner** [comment] 2018-08-29 14:27
I am also seeing this problem where the certificates/deploy_ca.yml tasks are being skipped in an native HA 
co located etcd config. There does not appear to be any clear reason why ansible is skipping these tasks.

**Closed** 2020-07-26 07:37 UTC
Labels: lifecycle/rotten
