### ISSUE TITLE
Docker service on master could not be started

### ISSUE THREAD

**Issue by cw1** [openshift/openshift-ansible#932] opened 2015-11-18 10:10 UTC
After running `bin/cluster create aws my_super_cool_cluster` the script executes, but failed at starting the docker service on master node:
```
TASK: [docker | enable and start the docker service] ************************** 
changed: [gitmate-node-compute-3d445]
changed: [gitmate-node-compute-54454]
changed: [gitmate-node-infra-71737]
failed: [gitmate-master-fa9dc] => {"failed": true}
msg: Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
```

Output of `systemctl status docker.service`:
```
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: failed (Result: timeout) since Mi 2015-11-18 09:53:10 UTC; 5min ago
     Docs: http://docs.docker.com
 Main PID: 30008
```
journald's output is only `No journal files were found.`

I'm also unable to start the docker service manually with `sudo systemctl start docker.service` -> same status.
After reboot, docker daemon is started automatically (of course after installation has failed):
```
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: activating (start) since Mi 2015-11-18 10:07:50 UTC; 14s ago
     Docs: http://docs.docker.com
 Main PID: 1429 (docker)
   CGroup: /system.slice/docker.service
           ├─1429 /usr/bin/docker daemon --selinux-enabled
           └─2084 mkfs.ext4 -E nodiscard,lazy_itable_init=0,lazy_journal_init=0 /dev/mapper/docker-202:1-41981450-base
```

BTW: starting of the docker daemon works on the other nodes.

**Comment by menren** [comment] 2015-11-18 10:34
Hello Cw1, we discussed about this issue earlier : https://github.com/openshift/openshift-ansible/issues/916
I created a PR to fix that : https://github.com/openshift/openshift-ansible/pull/933

**Comment by detiber** [comment] 2015-11-18 14:46
@brenton please close, as this is a duplicate of https://github.com/openshift/openshift-ansible/issues/916

**Closed** 2015-11-18 14:51 UTC
