### ISSUE TITLE
mkdir /usr/bin/docker-current: read-only file system

### ISSUE THREAD

**Issue by jprovaznik** [openshift/openshift-ansible#1921] opened 2016-05-19 09:58 UTC
When deploying on atomic host, origin-node service fails to start with error:
May 19 09:54:36 localhost origin-node: Error response from daemon: Cannot start container eef72ca72eecdf33a559c72a7b046c627340fc1adee3516fe5937fb5f06af750: mkdir /usr/bin/docker-current: read-only file system

docker-current volume was introduced in commit https://github.com/openshift/openshift-ansible/commit/3bf0e22fe10cba6102b07f2906b782eda69c7590

**Comment by maci0** [comment] 2016-05-19 10:09
this is strange. why would it try to create a directory there ?
I tested it exclusively on RHEL-AH and it worked just fine for me.
Are you on the latest version of RHEL-AH ?
I've only tested with that one.

**Comment by jprovaznik** [comment] 2016-05-19 10:18
I used an older atomic host image which is probably the problem, I'll try with the newest. Thanks for info.

**Comment by maci0** [comment] 2016-05-19 10:21
@sdodson havent thought about that... do we need some condition which checks whether we are running an old version which does not have docker-current and the wrapper script yet ?
or are we simply saying we support the latest version of RH-provided docker only ?

**Comment by sdodson** [comment] 2016-05-19 13:08
@maci0 when you add a volume and it doesn't exist docker will try to create it as a directory. We need a way to check if it exists and if so only then add it as a volume. I don't know how to do that.

**Comment by sdodson** [comment] 2016-05-19 13:10
@rhatdan any way to tell docker -v to ignore it if the source doesn't exist rather than trying to create it?

@maci0 we could try some ExecPreStart script to see if it exists and if it does export an environment variable that contains "-v /usr/bin/docker-current:/usr/bin/docker-current" otherwise set to "" then include that variable in the docker run command?

**Comment by rhatdan** [comment] 2016-05-19 13:54
@sdodson No, I don't think there is a way to ignore the source.

Why not mount /usr/bin/docker-current on /usr/bin/docker?

**Comment by maci0** [comment] 2016-05-19 14:23
@rhatdan will that not just fail the same way with older docker packages that don't ship docker-current?

anyway, the OSE 3.2 product documentation explicitly mentions that atomic host should be updated

**Comment by rhatdan** [comment] 2016-05-19 14:29
Yes.  I think ansible should check for the existence of docker-current and fail over to docker.

**Comment by detiber** [comment] 2016-05-19 14:42
So, I don't think Ansible managing it is the way to go, since we can't guarantee that a user will be maintaining their environments using Ansible and upgrading from docker-1.9.1-25 to docker-1.9.1-40 after installing will cause an issue.

I'm going to play around with doing the conditional from facilities available in the systemd unit file we are creating.

**Comment by maci0** [comment] 2016-05-19 19:22
again, or just don't bind-mount docker at all and use whatever client version is available within the node container image. Which shouldn't break, unless the API changes.
I've tested it with docker 1.9.1-40 on the host and 1.9.1-25 inside the image and it worked just fine.

**Comment by detiber** [comment] 2016-05-19 21:22
@maci0 the issue is that the images could potentially be built with a newer version of docker than is on the host, so docker 1.8 on the host and docker 1.9 in the container would be problematic.

Since we cannot simply upgrade docker on an atomic host when installing/upgrading, I think handling the bind mounts is the safest way to go.

**Comment by maci0** [comment] 2016-05-20 06:17
@detiber Do we support OSE 3.2 with docker 1.8 ?

**Comment by sdodson** [comment] 2016-05-20 13:20
@maci0 no, but docker-1.9.1-25 lacks /usr/bin/docker-current there's also the concern that on non atomic hosts if we blindly mount /usr/bin/docker-current when it doesn't exist then docker will create a directory at that path. While the node will work it will block upgrading to docker-1.9.1-40 or later (I think, I'd need to test this to be sure).

**Comment by detiber** [comment] 2016-05-20 13:42
So, thinking a bit more about the problem. Others have solved similar issues by using one unit to generate an env file that is used by another unit. It seems like that is a better approach than relying on undocumented behavior around execprestart or relying on the client in the image.

**Comment by abutcher** [comment] 2016-05-24 20:50
Resolved by #1941

**Closed by abutcher** 2016-05-24 20:50 UTC
