### ISSUE TITLE
Nodes do not get labelled post install

### ISSUE THREAD

**Issue by shilpapadgaonkar** [openshift/openshift-ansible#406] opened 2015-07-31 08:09 UTC
Hello Team,
I am installing a multi-node Openshift Enterprise and post install, we find that the nodes do not get labelled as specified in the inventory.
This was working when we tested the install on Beta. 

Thanks,
Shilpa

**Comment by detiber** [comment] 2015-08-03 06:09
@twiest this is a duplicate of https://github.com/openshift/openshift-ansible/issues/305, please close

**Closed** 2015-08-03 06:52 UTC
