### ISSUE TITLE
some tasks that should be verifying user/namespace are not

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-ansible#1344] opened 2016-02-05 18:46 UTC
I was running playbooks and got this error:

```
TASK: [Get master service ip] ************************************************* 
failed: [master1.example.com] => {"changed": true, "cmd": ["oc", "get", "-o", "template", "svc", "kubernetes", "--template={#.spec.clusterIP#}"], "delta": "0:00:00.356197", "end": "2016-02-05 13:42:50.726884", "rc": 1, "start": "2016-02-05 13:42:50.370687", "warnings": []}
stderr: Error from server: services "kubernetes" not found

FATAL: all hosts have already failed -- aborting
```

I realized quickly that this is because the root account on master1 is not logged in as `system:admin` presently and/or is not in the default project, which explains why the `kubernetes` service isn't found.

So, we may need to scrub to make sure that tasks that need to be performed as `system:admin` are, and that we prefix with namespaces.

**Comment by sdodson** [comment] 2016-02-05 18:48
dupe of #631

**Comment by abutcher** [comment] 2016-02-05 19:33
This task was removed in https://github.com/openshift/openshift-ansible/pull/1012

**Comment by tbielawa** [comment] 2016-11-15 19:53
Dupe. Also we use the admin.kubeconfig whenever possible now.

**Closed by tbielawa** 2016-11-15 19:53 UTC
