### ISSUE TITLE
openshift_manageiq failing in OpenShift pull request testing on release-3.6

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#4883] opened 2017-07-27 02:17 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/4854/consoleFull#-63476801158b6e51eb7608a5981914356

```
TASK [openshift_manageiq : Create Admin and Image Inspector Service Account] ***
Wednesday 26 July 2017  23:05:07 +0000 (0:00:08.510)       0:16:13.058 ******** 
failed: [ci-prtest-5a37c28-4854-ig-m-npmg] (item=management-admin) => {"failed": true, "item": "management-admin", "msg": {"cmd": "/bin/oc create -f /tmp/management-admin-3M8LCw -n management-infra", "results": {}, "returncode": 1, "stderr": "Error from server (NotFound): error when creating \"/tmp/management-admin-3M8LCw\": namespaces \"management-infra\" not found\n", "stdout": ""}}
failed: [ci-prtest-5a37c28-4854-ig-m-npmg] (item=inspector-admin) => {"failed": true, "item": "inspector-admin", "msg": {"cmd": "/bin/oc create -f /tmp/inspector-admin-s0o_In -n management-infra", "results": {}, "returncode": 1, "stderr": "Error from server (NotFound): error when creating \"/tmp/inspector-admin-s0o_In\": namespaces \"management-infra\" not found\n", "stdout": ""}}
```

Started failing a few hours ago.  I would not expect management-infra to be created by default unless we are setting up manageiq.  Is this a default config change?  I couldn't find out how this was enabled by looking at the commits.  This is for the release-3.6 code branch which should be building ansible release-3.6 (which I am double checking right now)

**Comment by brenton** [comment] 2017-08-01 14:57
This was likely a flake caused by a completely unrelated problem. You can see just before the failure that the namespace was created.  This code hasn't changed since OCP 3.1.  However, it does expose the fact that it needs to be deprecated.  OCP 3.6 has a new way to deploy CFME on top of OpenShift.  The card tracking that work is here:

https://trello.com/c/jeXsLUwi/494-we-should-only-have-one-way-to-install-cfme

**Comment by tbielawa** [comment] 2017-08-16 12:39
1. We figured out that this does not need to be deprecated. That role is what allows MIQ to manage Open Shift clusters
2. @smarterclayton is this still a problem?

**Comment by brenton** [comment] 2017-08-16 13:24
I looked at all the failures in the jenkins history on https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/ and did not see it happening.  While this only shows about 48 hours of builds it's the best way I know to check if this is still a problem.  There have been plenty successful runs so at best this was an intermittent problem.

@enoodle, Can you think of anything that could have caused this failure?

**Comment by enoodle** [comment] 2017-08-16 13:37
@brenton My only guess is that some thing caused the "management-infra" namespace not to be created and this caused those failures.

**Comment by brenton** [comment] 2017-08-16 14:01
@enoodle, Sorry I wasn't more clear.  That was our suspicion too.  Unfortunately we no longer have the logs but when I checked the them they indicated that the namespace creation was successful.  I'm guessing you haven't seen this problem.

**Comment by enoodle** [comment] 2017-08-16 14:04
@brenton No. This is a pretty straight forward role, creating a namespace, then creating SAs and cluster roles, then assigning roles.
In our team we are using it almost daily and haven't encountered this problem yet.

**Comment by brenton** [comment] 2017-08-16 14:05
OK, I honestly think we should close this issue for now then.  Thanks.

**Closed by brenton** 2017-08-16 14:05 UTC
Labels: priority/P2
