### ISSUE TITLE
Upgrade error: SDN node startup failed: could not get EgressNetworkPolicies

### ISSUE THREAD

**Issue by macedogm** [openshift/openshift-ansible#2523] opened 2016-09-28 20:18 UTC
Hi. I tried to run an ansible playbook upgrade from Origin 1.2.1 to 1.3.0 in a cluster with 01 load balance, 03 masters and 03 nodes over CentOS 7, but it failed while restarting origin-node service.

##### Version
Git repo version: openshift-ansible-3.4.2-1-22-g3391904
Ansible version: ansible 2.2.0

##### Steps To Reproduce
1. Run a playbook upgrade: ansible-playbook openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_3/upgrade.yml

2. Upgrade fail with error:
```
TASK [Restart node service] ****************************************************
fatal: [tst-openshift-master01-poa.rbs.com.br]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}
fatal: [tst-openshift-master03-poa.rbs.com.br]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}
fatal: [tst-openshift-master02-poa.rbs.com.br]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=18   changed=10   unreachable=0    failed=0   
openshift-tst.rbs.com.br   : ok=56   changed=0    unreachable=0    failed=0   
tst-openshift-master01-poa.rbs.com.br : ok=115  changed=3    unreachable=0    failed=1   
tst-openshift-master02-poa.rbs.com.br : ok=115  changed=3    unreachable=0    failed=1   
tst-openshift-master03-poa.rbs.com.br : ok=115  changed=3    unreachable=0    failed=1   
tst-openshift-node01-poa.rbs.com.br : ok=81   changed=1    unreachable=0    failed=0   
tst-openshift-node02-poa.rbs.com.br : ok=81   changed=1    unreachable=0    failed=0   
tst-openshift-node03-poa.rbs.com.br : ok=81   changed=1    unreachable=0    failed=0  
```

##### Current Result
Upgrade from 1.2.1 to 1.3.0 failed.

##### Expected Result
OpenShift Origin running version 1.3.0

##### Additional Information
journalctl -xe has the following entry:

```
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br systemd[1]: Starting Origin Node...
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: W0928 17:16:42.622859   43057 node_config.go:436] either there is network plugin mismatch between OpenShift node("redhat/openshift-ovs-multitenant") and master or OpenShift master is running an older version where we did not persist plugin name
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.623437   43057 docker.go:329] Start docker client with request timeout=2m0s
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.633703   43057 node.go:42] Initializing SDN node of type "redhat/openshift-ovs-multitenant" with configured hostname "tst-openshift-master01-poa.rbs.com.br" (IP ""), iptables sync period "30s"
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.634513   43057 start_node.go:298] Starting node tst-openshift-master01-poa.rbs.com.br (v1.3.0)
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.639054   43057 start_node.go:307] Connecting to API server https://tst-openshift-lb01-poa.rbs.com.br:8443
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.641321   43057 docker.go:309] Connecting to docker on unix:///var/run/docker.sock
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.641364   43057 docker.go:329] Start docker client with request timeout=0
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br docker-current[3128]: time="2016-09-28T17:16:42.642620800-03:00" level=info msg="{Action=_ping, LoginUID=4294967295, PID=43057}"
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.643156   43057 node.go:138] Connecting to Docker at unix:///var/run/docker.sock
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.697895   43057 manager.go:138] cAdvisor running in container: "/system.slice/origin-node.service"
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.722685   43057 subnets.go:247] Found local HostSubnet tst-openshift-master01-poa.rbs.com.br (host: "tst-openshift-master01-poa.rbs.com.br", ip: "192.168.203.221", subnet: "172.16.3.0/24")
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.738714   43057 vnids_node.go:105] Associate netid 0 to namespace "default"
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.738755   43057 vnids_node.go:105] Associate netid 13 to namespace "logging"
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.738768   43057 vnids_node.go:105] Associate netid 12 to namespace "management-infra"
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.738778   43057 vnids_node.go:105] Associate netid 11 to namespace "openshift"
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.738788   43057 vnids_node.go:105] Associate netid 10 to namespace "openshift-infra"
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.738798   43057 vnids_node.go:105] Associate netid 15 to namespace "test-app"
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.738807   43057 vnids_node.go:105] Associate netid 18 to namespace "zembrzuski-fooo"
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: I0928 17:16:42.743292   43057 controller.go:544] AddHostSubnetRules for tst-openshift-master02-poa.rbs.com.br (host: "tst-openshift-master02-poa.rbs.com.br", ip: "192.168.203.222", subnet: "172.16.2.0/24")
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br origin-node[43057]: F0928 17:16:42.749692   43057 node.go:343] error: SDN node startup failed: could not get EgressNetworkPolicies: the server could not find the requested resource
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br systemd[1]: origin-node.service: main process exited, code=exited, status=255/n/a
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br systemd[1]: Failed to start Origin Node.
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br systemd[1]: Unit origin-node.service entered failed state.
Sep 28 17:16:42 tst-openshift-master01-poa.rbs.com.br systemd[1]: origin-node.service failed.
```

**Comment by dgoodwin** [comment] 2016-10-06 12:01
I thought we had this fixed by moving reconcile-cluster-roles in between master upgrade, and node upgrade, but it looks like something is still wrong.

Others have reported that restarting master services, and then re-running the upgrade will let it complete successfully. It seems like reconcile cluster roles may need a master restart to take effect for this EgressNetworkPolicy. Trying to track down someone who might know more.

**Comment by danwinship** [comment] 2016-10-06 12:22
The problem isn't with reconciling, it's that the 1.2 server doesn't have any concept of EgressNetworkPolicies, so when the 1.3 node tries to fetch them from it, it gets a 404, which the code is not expecting. Restarting the master fixes this because you're restarting to the 1.3 master.

I had thought you had to upgrade (and restart) the master before upgrading the nodes?

**Comment by dgoodwin** [comment] 2016-10-06 12:35
@danwinship FWIW upgrade is very much a phased affair with openshift-ansible, we upgrade all masters first, then reconcile, then move onto all nodes. By the time a node is restarting the control plane definitely should be up to 1.3 already.

**Comment by dgoodwin** [comment] 2016-10-06 12:46
Hmm, I might be seeing a way that the masters could skip restarts, investigating some more.

**Comment by dgoodwin** [comment] 2016-10-06 12:46
If anyone has a full ansible log from one of these failed upgrades it would be immensely useful.

**Comment by macedogm** [comment] 2016-10-06 13:02
Hi @dgoodwin. I can send you a full log. Do you have a private e-mail, 
or other way, to send it? I don't want to expose sensitive information 
from my environment.

**Comment by dgoodwin** [comment] 2016-10-06 13:05
@macedogm yes please, dgoodwin@redhat.com, thanks!

**Comment by macedogm** [comment] 2016-10-06 13:11
@dgoodwin will send it ASAP. Do you need any special or debug parameter 
when I run the playbook?

**Comment by dgoodwin** [comment] 2016-10-06 13:20
@macedogm I don't think so no provided it reproduces the failure, mainly I'm looking to see if the master services got restarted after they were updated. -vvv can't hurt I guess.

**Comment by macedogm** [comment] 2016-10-06 13:50
@dgoodwin I just sent the mail. Please, let me know if you need more 
info or tests.

**Comment by dgoodwin** [comment] 2016-10-13 17:24
I believe this is fixed in latest master.

**Closed by dgoodwin** 2016-10-13 17:25 UTC

**Comment by macedogm** [comment] 2016-10-15 21:11
@dgoodwin It worked! Thanks for the help!
