### ISSUE TITLE
We should install and configure etcdctl along side kube

### ISSUE THREAD

**Issue by jayunit100** [openshift/openshift-ansible#1329] opened 2016-02-03 21:28 UTC
After a few hours of trying a myriad of combinations of certs, keys, etc, I finally found out that the only way to connect to etcd on my cluster was

- using the fqdn
- with 4001 as the port
- using `https://` on the `-C` option to etcdctl

Lets

- install etcdctl as part of the ansible setup
- configure `/etc/etcd/...` so that users can easily run `etcdctl` from the master without any fuss.

```
[16:21:28]  <jayunit100>	sudo etcdctl -C https://ip-172-18-9-81.ec2.internal:4001 --ca-file=/etc/origin/master/ca.crt --cert-file=/etc/origin/master/master.etcd-client.crt --key-file=/etc/origin/master/master.etcd-client.key ls / # for the record
[16:22:17]  <jdetiber>	you can see how often I drop down into etcd :)  was looking at notes from before last years Summit
[16:22:20]  <jayunit100>	0.0.0.0 FAILS, missing HTTP FAILS, 127.0.0.1 FAILS, you gotta have fqdn+https  :) lessonlearned
```
Thanks to @detiber  for helping me track this down!

**Comment by timothysc** [comment] 2016-02-03 21:30
dupe of https://github.com/openshift/openshift-ansible/issues/814

**Closed** 2016-02-03 21:30 UTC
