### ISSUE TITLE
No package matching 'origin-docker-excluder-1.5.0*

### ISSUE THREAD

**Issue by magick93** [openshift/openshift-ansible#3864] opened 2017-04-06 09:18 UTC
## Description

Trying to install OpenShift Origin v1.5.0-rc.0 on a single node.

### Version

Please put the following version information in the code block
indicated below.

 `ansible --version` is ansible 2.2.0.0

 `git describe` is openshift-ansible-3.6.16-1-2-gb930b55

### Expected Results
Expect that I can install OpenShift Origin using openshift-ansible.

### Observed Results
Fails with error `No package matching 'origin-docker-excluder-1.5.0*`. More detailed output below.

```
TASK [openshift_excluder : Install docker excluder] ****************************
task path: /root/openshift-ansible/roles/openshift_excluder/tasks/install.yml:7
Running yum
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/packaging/os/yum.py
<console.mydomain.com> ESTABLISH SSH CONNECTION FOR USER: root
<console.mydomain.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r console.mydomain.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1491469874.83-111509194057108 `" && echo ansible-tmp-1491469874.83-111509194057108="` echo $HOME/.ansible/tmp/ansible-tmp-1491469874.83-111509194057108 `" ) && sleep 0'"'"''
<console.mydomain.com> PUT /tmp/tmpHffH7n TO /root/.ansible/tmp/ansible-tmp-1491469874.83-111509194057108/yum.py
<console.mydomain.com> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[console.mydomain.com]'
<console.mydomain.com> ESTABLISH SSH CONNECTION FOR USER: root
<console.mydomain.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r console.mydomain.com '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1491469874.83-111509194057108/ /root/.ansible/tmp/ansible-tmp-1491469874.83-111509194057108/yum.py && sleep 0'"'"''
<console.mydomain.com> ESTABLISH SSH CONNECTION FOR USER: root
<console.mydomain.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt console.mydomain.com '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1491469874.83-111509194057108/yum.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1491469874.83-111509194057108/" > /dev/null 2>&1 && sleep 0'"'"''
fatal: [console.mydomain.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "conf_file": null, 
            "disable_gpg_check": false, 
            "disablerepo": null, 
            "enablerepo": null, 
            "exclude": null, 
            "install_repoquery": true, 
            "list": null, 
            "name": [
                "origin-docker-excluder-1.5.0*"
            ], 
            "state": "present", 
            "update_cache": false, 
            "validate_certs": true
        }
    }, 
    "msg": "No package matching 'origin-docker-excluder-1.5.0*' found available, installed or updated", 
    "rc": 126, 
    "results": [
        "No package matching 'origin-docker-excluder-1.5.0*' found available, installed or updated"
    ]
}
	to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
console.mydomain.com   : ok=93   changed=0    unreachable=0    failed=1   
localhost                  : ok=7    changed=0    unreachable=0    failed=0   

[root@CentOS-73-64-minimal ~]# 

```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Operating system - CentOS Linux release 7.3.1611 (Core) 
* Inventory file:
```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
containerized=true
openshift_release=v1.5.0
openshift_image_tag=v1.5.0-rc.0
openshift_public_hostname=console.mydomain.com
openshift_master_default_subdomain=apps.console.mydomain.com
openshift_hosted_metrics_deploy=true




[masters]
console.mydomain.com openshift_schedulable=true

[nodes]
console.mydomain.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true
```

**Comment by sosiouxme** [comment] 2017-04-06 14:09
Had this problem myself this morning. I noticed that in /etc/yum.conf origin-docker-excluder was itself excluded. Looks like origin-excluder is getting installed first and preventing the installation of origin-docker-excluder.

**Comment by magick93** [comment] 2017-04-06 15:58
Ok.

Is there a workaround for this issue?

**Comment by mtnbikenc** [comment] 2017-04-06 16:48
See https://github.com/openshift/openshift-ansible/pull/3863

**Comment by magick93** [comment] 2017-04-07 08:34
Ive tried pulling the latest master and running again, but am still getting the same error.

**Comment by magick93** [comment] 2017-04-07 08:50
I managed to work around this issue by using advice from https://github.com/openshift/openshift-ansible/issues/3705#issuecomment-287742402

**Comment by rhcarvalho** [comment] 2017-04-11 11:35
@magick93 | @sosiouxme | @mtnbikenc | @sdodson is it fair to close this issue as a duplicate of #3705?

**Comment by magick93** [comment] 2017-04-11 11:42
is it fair to close this issue as a duplicate of #3705
> <https://github.com/openshift/openshift-ansible/issues/3705>?
>

Yes

**Closed** 2017-04-11 11:53 UTC
