### ISSUE TITLE
Openshift origin installation fails on Centos because of expired ssl certificates

### ISSUE THREAD

**Issue by anujjamwal** [openshift/openshift-ansible#1833] opened 2016-04-28 09:30 UTC

**Comment by abutcher** [comment] 2016-04-28 15:01
Hey @anujjamwal could you provide some context to the failure? Which certificates were expired? Was this a new installation? Can you reproduce the issue? Providing your inventory can also help us figure out what went wrong.

**Comment by anujjamwal** [comment] 2016-04-29 10:24
I tried directly installing on vagrant vm and got the following error


```
[vagrant@lb tmp]$ ansible-playbook openshift-ansible/playbooks/byo/config.yml
ERROR! 'vars_files' is not a valid attribute for a PlaybookInclude

The error appears to have been in '/tmp/openshift-ansible/playbooks/byo/openshift-cluster/config.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

 ---
- include: ../../common/openshift-cluster/config.yml
  ^ here
```
I then tried using the url for install

> sh <(curl -s https://install.openshift.com/origin-m4)

and error 
```
reflight check: verifying system and resource availability.

Checking lb.openshift.localcloud.com:
* Target host is running CentOS
* Located getenforce... can invoke 'getenforce' with sudo
* ERROR: SELinux is disabled. You must enable SELinux on this host.
* Located yum... can invoke 'yum' with sudo
Error: No matching Packages to list
* The 'puppet' package is not installed on this host.
* openssh-clients RPM is installed.
Error: No matching Packages to list
* The 'bind' package is not installed on this host.
Error: No matching Packages to list

The following RPMs are required, but not installed on this host:
* puppet
* bind
Do you want to want me to try to install them for you? (y/n/q) y

Checking availability of 'puppet' RPM... Error: No matching Packages to list
not available.
Attempting to install the puppet repo RPM... warning: /var/tmp/rpm-tmp.xg6upV: Header V4 RSA/SHA1 Signature, key ID 4bd6ec30: NOKEY
repo added.
Attempting to install puppet... warning: rpmts_HdrFromFdno: Header V4 RSA/SHA1 Signature, key ID 4bd6ec30: NOKEY
Importing GPG key 0x4BD6EC30:
 Userid : Puppet Labs Release Key (Puppet Labs Release Key) <info@puppetlabs.com>
 Package: puppetlabs-release-6-12.noarch (installed)
 From   : /etc/pki/rpm-gpg/RPM-GPG-KEY-puppetlabs
Warning: RPMDB altered outside of yum.
success!

Checking availability of 'bind' RPM... available.
Attempting to install... success!

The deployment check was not successful. See above for specific issues.
oo-install exited; removing temporary assets.
```

**Comment by anujjamwal** [comment] 2016-04-29 10:25
The Vagrantfile

```ruby
master_count = 1
node_count = 1
box = 'puppetlabs/centos-6.6-64-nocm'

setup = <<script
sudo su -

yum install -y wget git net-tools bind-utils iptables-services bridge-utils bash-completion epel-release

yum clean all
yum -y update

sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo
yum -y --enablerepo=epel install ansible pyOpenSSL

sudo tee /etc/yum.repos.d/docker-main.repo <<-'EOF'
[docker-main-repo]
name=Docker main Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/6
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF

yum install -y docker-engine
service docker start
chkconfig docker on
exit
script

installer = <<script
sudo su

cd /tmp
git clone https://github.com/openshift/openshift-ansible

cat <<EOF>> /etc/ansible/hosts
# Create an OSEv3 group that contains the master, nodes, etcd, and lb groups.
# The lb group lets Ansible configure HAProxy as the load balancing solution.
# Comment lb out if your load balancer is pre-configured.
[OSEv3:children]
masters
nodes
etcd
lb

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=vagrant
deployment_type=origin

# Uncomment the following to enable htpasswd authentication; defaults to
# DenyAllPasswordIdentityProvider.
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# Native high availbility cluster method with optional load balancer.
# If no lb group is defined installer assumes that a load balancer has
# been preconfigured. For installation the value of
# openshift_master_cluster_hostname must resolve to the load balancer
# or to one or all of the masters defined in the inventory if no load
# balancer is present.
openshift_master_cluster_method=native
openshift_master_cluster_hostname=openshift-cluster.localcloud.com
openshift_master_cluster_public_hostname=openshift-cluster.localcloud.com

# override the default controller lease ttl
#osm_controller_lease_ttl=30

# host group for masters
[masters]
#{(1..master_count).map {|id| "master#{id}.openshift.localcloud.com\n" }}

# host group for etcd
[etcd]
#{(1..master_count).map {|id| "master#{id}.openshift.localcloud.com\n" }}

# Specify load balancer host
[lb]
lb.openshift.localcloud.com

# host group for nodes, includes region info
[nodes]
master[1:#{master_count}].openshift.localcloud.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
node1.openshift.localcloud.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
EOF

ansible-playbook openshift-ansible/playbooks/byo/config.yml
script

Vagrant.configure('2') do |config|

	(1..master_count).each do |id|
		config.vm.define "master#{id}" do |master|
			master.vm.box = box
			master.vm.hostname = "master#{id}.openshift.localcloud.com"
			master.vm.network 'private_network', ip: "192.168.56.#{id+100}"
			master.vm.provision 'shell', inline: setup
		end
	end

	(1..node_count).each do |id|
		config.vm.define "node#{id}" do |master|
			master.vm.box = box
			master.vm.hostname = "node#{id}.openshift.localcloud.com"
			master.vm.network 'private_network', ip: "192.168.56.#{id+120}"
			master.vm.provision 'shell', inline: setup
		end
	end

	config.vm.define "lb" do |master|
		master.vm.box = box
		master.vm.hostname = "lb.openshift.localcloud.com"
		master.vm.network 'private_network', ip: "192.168.56.100"
		master.vm.provision 'shell', inline: setup
		master.vm.provision 'shell', inline: installer
	end
end

```

**Comment by abutcher** [comment] 2016-04-29 14:17
@anujjamwal Based on the errors it looks like you're using ansible 2.0. Could you confirm?

We're in the process of porting our playbooks to ansible v2 but until that work is complete, we require ansible 1.9.4. If you're using 2.0, could you try running with 1.9.4?

We're tracking ansible v2 support here: https://github.com/openshift/openshift-ansible/issues/686

**Comment by abutcher** [comment] 2016-04-29 16:10
@anujjamwal Also, origin m4 (openshift v2) represents origin prior to incorporating docker and kubernetes. openshift-ansible is targeted at configuring openshift v3.

https://blog.openshift.com/how-we-number-openshift-origin-and-enterprise-releases/

**Comment by anujjamwal** [comment] 2016-05-02 04:21
Hi Andrew
Changing the ansible issue got the installer running. It is however still failing. I dont know if this is the right place for this, but posting the screenshots.
<img width="832" alt="screen shot 2016-05-02 at 9 43 47 am" src="https://cloud.githubusercontent.com/assets/1766163/14947099/ee54c726-104a-11e6-8b81-5bf384990772.png">

Setup:
3 Centos 7 VM running in Virtual Box connected with NatNetwork
<img width="804" alt="screen shot 2016-05-02 at 9 50 04 am" src="https://cloud.githubusercontent.com/assets/1766163/14947117/4722e432-104b-11e6-84fa-9e7d19232b5d.png">

**Comment by rhcarvalho** [comment] 2016-11-03 13:38
@abutcher @anujjamwal is there something to be done being tracked by this issue? If not I'd suggest we close it.


BTW I noticed the Vagrantfile installs Docker from `dockerproject.org`, which according to the [README](https://github.com/openshift/openshift-ansible#openshift-ansible) do not fulfill the requirements.

**Comment by abutcher** [comment] 2016-11-03 20:40
@rhcarvalho Ack, let's open a separate issue for that.

**Closed by abutcher** 2016-11-03 20:40 UTC
Labels: kind/bug, priority/P3
