### ISSUE TITLE
Single etcd install fails on release-3.7

### ISSUE THREAD

**Issue by mcanevet** [openshift/openshift-ansible#6087] opened 2017-11-10 12:03 UTC
#### Description

On a single etcd node install, ansible-playbook fails with 

    "Unable to restart service origin-master-api: Job for origin-master-api.service failed because the control process exited with error code. See \"systemctl status origin-master-api.service\" and \"journalctl -xe\" for details.\n"

When connecting to the master, it looks like there is a certificate issue in etcd:
```
# systemctl status etcd.service 
...
nov. 10 11:17:21 ip-192-168-1-15.infrastructure.internal systemd[1]: Started Etcd Server.
nov. 10 11:17:21 ip-192-168-1-15.infrastructure.internal etcd[13473]: Failed to dial 192.168.1.15:2379: connection error: desc = "transport: remote error: tls: bad certificate"; please retry.
```

##### Version

```
# ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

# git describe
openshift-ansible-3.7.5-1
```

##### Steps To Reproduce
1. Launch ansible-playbook with an inventory file containing a single master and an single etcd on master

##### Expected Results

ansible-playbook should work

##### Observed Results
ansible-playbook fails with:
```
Unable to restart service origin-master-api: Job for origin-master-api.service failed because the control process exited with error code. See "systemctl status origin-master-api.service" and "journalctl -xe" for details.
```

##### Additional Information

It works fine in multi master install with etcd on each master.

**Comment by abutcher** [comment] 2017-11-10 20:29
We're mentioned here in this etcd issue for what seems to be the same problem although it's non fatal in their case. https://github.com/coreos/etcd/issues/8603#issuecomment-341508947

**Comment by abutcher** [comment] 2017-11-10 20:30
cc: @ingvagabund

**Comment by abutcher** [comment] 2017-11-10 21:57
I thought I had reproduced this but I just had an old haproxy service blocking my master from listening on port 8443.

@mcanevet Does etcd report `"cluster is healthy"` testing `cluster-health` using the peer and master client certificates?

```
etcdctl -C https://${ETCD_CA_HOST}:2379 \
           --ca-file=/etc/etcd/ca.crt  \
           --cert-file=/etc/etcd/peer.crt \
           --key-file=/etc/etcd/peer.key \
           cluster-health
```

```
etcdctl -C https://${ETCD_CA_HOST}:2379 \
           --ca-file=/etc/origin/master/master.etcd-ca.crt \
           --cert-file=/etc/origin/master/master.etcd-client.crt \
           --key-file=/etc/origin/master/master.etcd-client.key \
           cluster-health
```

**Comment by eliu** [comment] 2017-11-14 05:04
I had the similar issue. Any updates on this?

**Comment by wenzowski** [comment] 2017-12-01 18:20
In my `/etc/orgigin/master/master-config.yaml` I see `etcdClientInfo.urls: [https://openshift.local:2379]` 
...but in `/etc/etcd/etcd.conf` I see `ETCD_LISTEN_CLIENT_URLS=192.168.202.221:2379`
which is the ip assigned to `ens32` while `openshift.local` resolves to the ip of `ens33`

**Comment by wenzowski** [comment] 2017-12-01 18:28
grepping for this, I see `etcdClientInfo.urls` is overridden in `roles/openshift_master/tasks/configure_external_etcd.yml` so no surprise it works on external etcd

**Comment by wenzowski** [comment] 2017-12-01 18:33
seems like the problem is [here](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/library/openshift_facts.py#L573)

**Closed** 2020-07-19 07:12 UTC
Labels: lifecycle/rotten
