### ISSUE TITLE
Invalid boolean conversion for extraAuthorizeParameters include_granted_scopes

### ISSUE THREAD

**Issue by bagnaram** [openshift/openshift-ansible#2454] opened 2016-09-15 11:51 UTC
When trying to define an OpenIDConnect ID provider in Ansible hosts by setting include_granted_scopes. If the value is “true” with the double quotes then the definition is invalid. 

For instance extraAuthorizeParameters': {'include_granted_scopes': ‘\”true\"'} results in include_granted_scopes: false in the configuration.

The issue seems to be that the value of include_granted_scopes is evaluated as ansible_bool.

https://github.com/openshift/openshift-ansible/blob/b8e72ea2143834317043f19cbc3dddf8ad9047a5/filter_plugins/openshift_master.py#L388

**Comment by detiber** [comment] 2016-09-16 04:14
@bagnaram what is the goal of using the double quotes? I would expect for `{'include_granted_scopes': 'true'}` or `{'include_granted_scopes': true}` to produce the correct output in the master config.

**Comment by bagnaram** [comment] 2016-09-16 14:14
I think it is because the master-config expects the value as a string. include_granted_scopes: "true"
The boolean parser is likely evaluating the string constant as always true

**Comment by sdodson** [comment] 2016-12-01 19:54
I've moved this to P2 based on it not being a regression.

**Comment by adelton** [comment] 2017-09-13 08:48
The https://github.com/openshift/openshift-ansible/pull/5350 was merged but it probably is not the right change.

I've now tested

```
openshift_master_identity_providers=[{"name": "keycloak-true", "login": "true", "challenge": "false", "mappingMethod": "claim", "kind": "OpenIDIdentityProvider", "client_id": "openshift", "clientSecret": "Secret123", "extraAuthorizeParameters" : {"include_granted_scopes": "true"}, "claims": {"id": ["sub"]}, "urls": {"authorize": "http://idp.example.com/oauth2/v1/authorize", "token": "http://idp.example.com/oauth2/v1/token" }}]
```

where that `"true"` has replaced with various strings. Here's what gets stored in `/etc/origin/master/master-config.yaml` for the individual inputs.

With the original code:

```
Inventory file:                               master-config.yaml
"include_granted_scopes": "true"              include_granted_scopes: true
"include_granted_scopes": "yes"               include_granted_scopes: true
"include_granted_scopes": "'true'"            include_granted_scopes: false
"include_granted_scopes": "no"                include_granted_scopes: false
"include_granted_scopes": "false"             include_granted_scopes: false
"include_granted_scopes": "'false'"           include_granted_scopes: false
"include_granted_scopes": "jezek"             include_granted_scopes: false
```

With the patch from https://github.com/openshift/openshift-ansible/pull/5350 the results are

```
Inventory file:                               master-config.yaml
"include_granted_scopes": "true"              include_granted_scopes: '"true"'
"include_granted_scopes": "yes"               include_granted_scopes: '"true"'
"include_granted_scopes": "'true'"            include_granted_scopes: '"false"'
"include_granted_scopes": "no"                include_granted_scopes: '"false"'
"include_granted_scopes": "false"             include_granted_scopes: '"false"'
"include_granted_scopes": "'false'"           include_granted_scopes: '"false"'
"include_granted_scopes": "jezek"             include_granted_scopes: '"false"'
```

so we now have double quotes there which is not correct.

Of course, the question is if things like

```
"include_granted_scopes": "'true'"
"include_granted_scopes": "'false'"
```

should be supported.

So this issue should likely be reopened and it'd be nice to get some vote about what the output for the individual `openshift_master_identity_providers` entries should be. Then we can prepare correct patch.

My proposal for what should appear in `master-config.yaml` would be:

```
Inventory file:                               master-config.yaml
"include_granted_scopes": "true"              include_granted_scopes: 'true'
"include_granted_scopes": "yes"               include_granted_scopes: 'true'
"include_granted_scopes": "'true'"            include_granted_scopes: 'true'
"include_granted_scopes": '"true"'            include_granted_scopes: 'true'
"include_granted_scopes": "no"                include_granted_scopes: 'false'
"include_granted_scopes": "false"             include_granted_scopes: 'false'
"include_granted_scopes": "'false'"           include_granted_scopes: 'false'
"include_granted_scopes": "jezek"             include_granted_scopes: 'jezek'
```

**Comment by adelton** [comment] 2017-09-13 08:54
Alternatively we can go with just `"true"` and `"yes"` being taken as `'true'`. everything else being single-quoted `'false'`:

```
Inventory file:                               master-config.yaml
"include_granted_scopes": "true"              include_granted_scopes: 'true'
"include_granted_scopes": "yes"               include_granted_scopes: 'true'
"include_granted_scopes": "'true'"            include_granted_scopes: 'false'
"include_granted_scopes": "no"                include_granted_scopes: 'false'
"include_granted_scopes": "false"             include_granted_scopes: 'false'
"include_granted_scopes": "'false'"           include_granted_scopes: 'false'
"include_granted_scopes": "jezek"             include_granted_scopes: 'false'
```

**Comment by adelton** [comment] 2017-09-13 09:01
For the record, if we remove the whole block

```
        if 'extraAuthorizeParameters' in self._idp:
            if 'include_granted_scopes' in self._idp['extraAuthorizeParameters']:
                if ansible_bool(self._idp['extraAuthorizeParameters']['include_granted_scopes']):
                    self._idp['extraAuthorizeParameters']['include_granted_scopes'] = "true"
```

altogether, we get

```
Inventory file:                               master-config.yaml
"include_granted_scopes": "true"              include_granted_scopes: 'true'
"include_granted_scopes": "yes"               include_granted_scopes: 'yes'
"include_granted_scopes": "'true'"            include_granted_scopes: '''true'''
"include_granted_scopes": "no"                include_granted_scopes: 'no'
"include_granted_scopes": "false"             include_granted_scopes: 'false'
"include_granted_scopes": "'false'"           include_granted_scopes: '''false'''
"include_granted_scopes": "jezek"             include_granted_scopes: jezek
```

**Comment by ashcrow** [comment] 2017-09-13 14:07
> Of course, the question is if things like
> ```
> "include_granted_scopes": "'true'"
> "include_granted_scopes": "'false'"
> ```
> should be supported.

I don't think they should be tbh.

An alternate way of tackling this would be to allow the code to go back to it's simple boolean logic and have the template itself write the ``"true"`` or ``"false"`` string. It would avoid any new imports in the code and always provide a usable result.

With this idea ``"jezek"`` would be ``"false"`` as it isn't ``ansible_boolean`` ``True``.

@adelton @sdodson @mtnbikenc thoughts?

**Comment by sdodson** [comment] 2017-09-13 15:07
Based on https://bugzilla.redhat.com/show_bug.cgi?id=1488505#c6 we should just treat it as a string variable that we're passing through. We should not attempt to turn this into a boolean.

**Comment by ashcrow** [comment] 2017-09-13 15:47
@sdodson I think we have to do something as ansible will transform the string on it's own. Example: https://github.com/openshift/openshift-ansible/pull/5350#issuecomment-328654412

**Comment by adelton** [comment] 2017-09-15 11:52
> Based on https://bugzilla.redhat.com/show_bug.cgi?id=1488505#c6 we should just treat it as a string variable that we're passing through. We should not attempt to turn this into a boolean.

In that case, all that would be needed, really, is removing the whole block, to get results as shown in https://github.com/openshift/openshift-ansible/issues/2454#issuecomment-329104742. @detiber, the code was introduced back in 2015 via 3cbe7df8461e5514773e416d137980ce9bedf33d -- would you remember the reason behind conversion to boolean?

@sdodson, could you please reopen this issue?

**Comment by ashcrow** [comment] 2017-09-15 13:30
@adelton issue reopened. I'll open a PR to remove the block after morning meetings.

**Comment by adelton** [comment] 2017-09-15 13:37
I've filed https://github.com/openshift/openshift-ansible/pull/5427 with the block removal now.

**Closed** 2017-09-15 15:58 UTC
Labels: kind/bug, priority/P2
